"""Deterministic world-engine audit helpers."""

from __future__ import annotations


def build_cosmos_inventory_script(target: str) -> str:
    """Build a dependency-free world-engine readiness scanner."""
    return f'''\
"""Cosmos world-engine inventory script generated by analysis_cosmos."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

TARGET = {target!r}
SOURCE_SUFFIXES = {{".py", ".js", ".ts", ".tsx", ".jsx", ".yaml", ".yml"}}
STATE_PATTERNS = [
    (r"(?:position|coordinate|location|vector|matrix)\\s*[:=]", "空间/位置状态"),
    (r"(?:velocity|speed|acceleration|momentum|force)\\s*[:=]", "运动/力学状态"),
    (r"(?:mass|density|volume|temperature|energy)\\s*[:=]", "物理属性状态"),
    (r"(?:health|hunger|mood|personality|emotion)\\s*[:=]", "生命体内部状态"),
    (r"(?:relationship|trust|reputation|faction)\\s*[:=]", "社会关系状态"),
    (r"(?:memory|history|experience|knowledge)\\s*[:=]", "记忆/认知状态"),
    (r"(?:resource|inventory|currency|supply|demand)\\s*[:=]", "经济/资源状态"),
    (r"(?:rule|law|policy|constraint|boundary)\\s*[:=]", "规则/法则状态"),
    (r"(?:time|tick|frame|step|epoch|generation)\\s*[:=]", "时间/演化状态"),
]
GENERATION_PATTERNS = [
    (r"(?:random|rand|noise|stochastic|sample)\\s*\\(", "随机/采样"),
    (r"(?:procedural|generate|synthesize|create)\\s*\\(", "程序化生成"),
    (r"(?:mutate|evolve|crossover|breed)\\s*\\(", "进化/变异"),
    (r"(?:compose|assemble|combine|interpolate)\\s*\\(", "组合/插值"),
    (r"(?:seed|initialize|bootstrap)\\s*\\(", "种子/初始化"),
]
SOCIAL_PATTERNS = [
    (r"(?:agent|character|npc|entity|actor)", "智能体定义"),
    (r"(?:interact|communicate|message|talk|negotiate)\\s*\\(", "交互/通信"),
    (r"(?:observe|perceive|sense|detect)\\s*\\(", "感知/观测"),
    (r"(?:remember|recall|forget|memory|experience)", "记忆/经验"),
    (r"(?:decide|choose|plan|intend|goal)\\s*\\(", "决策/目标"),
    (r"(?:trade|exchange|barter|share)\\s*\\(", "交易/共享"),
]
OBSERVER_PATTERNS = [
    (r"(?:on_click|on_hover|on_touch|on_key|input)", "用户输入响应"),
    (r"(?:event|trigger|callback|listener|subscribe)", "事件驱动"),
    (r"(?:stream|real.?time|live|update|render)", "实时更新/渲染"),
    (r"(?:camera|viewport|frustum|visibility)", "视点/可见性"),
    (r"(?:lod|level.?of.?detail|chunk|region|tile)", "LOD/分块加载"),
    (r"(?:lazy|on.?demand|just.?in.?time|procedural)", "按需生成"),
]


def collect_sources(raw: str) -> list[Path]:
    path = Path(raw).expanduser().resolve()
    if not path.exists():
        return []
    if path.is_file() and path.suffix.lower() in SOURCE_SUFFIXES:
        return [path]
    if path.is_dir():
        return [
            child for child in list(path.rglob("*"))[:500]
            if child.is_file() and child.suffix.lower() in SOURCE_SUFFIXES
        ][:80]
    return []


def find_hits(source: str, patterns: list[tuple[str, str]]) -> list[dict[str, object]]:
    hits = []
    for line_no, line in enumerate(source.splitlines(), 1):
        for pattern, label in patterns:
            if re.search(pattern, line, re.IGNORECASE):
                hits.append({{"line": line_no, "label": label, "sample": line.strip()[:120]}})
    return hits


def score_file(
    state: list[dict[str, object]],
    generation: list[dict[str, object]],
    social: list[dict[str, object]],
    observer: list[dict[str, object]],
) -> float:
    state_labels = {{str(item["label"]) for item in state}}
    generation_labels = {{str(item["label"]) for item in generation}}
    social_labels = {{str(item["label"]) for item in social}}
    observer_labels = {{str(item["label"]) for item in observer}}
    return round(min(1.0, (
        min(len(state_labels) / 8.0, 1.0) * 0.30
        + min(len(generation_labels) / 5.0, 1.0) * 0.25
        + min(len(social_labels) / 5.0, 1.0) * 0.25
        + min(len(observer_labels) / 4.0, 1.0) * 0.20
    )), 3)


def build_genesis_contract(score: float) -> dict[str, object]:
    return {{
        "minimum_score": 0.7,
        "current_score": score,
        "ready_for_micro_world": score >= 0.7,
        "required_planes": [
            "state_dimension_schema",
            "procedural_generation_seed",
            "agent_memory_and_goals",
            "observer_driven_collapse",
            "compute_budget_guardrail",
        ],
    }}


def inspect_file(path: Path) -> dict[str, object]:
    try:
        source = path.read_text(encoding="utf-8", errors="ignore")
    except OSError as exc:
        return {{"path": str(path), "found": False, "error": str(exc)}}
    state = find_hits(source, STATE_PATTERNS)
    generation = find_hits(source, GENERATION_PATTERNS)
    social = find_hits(source, SOCIAL_PATTERNS)
    observer = find_hits(source, OBSERVER_PATTERNS)
    score = score_file(state, generation, social, observer)
    return {{
        "path": str(path),
        "found": True,
        "state": state[:80],
        "generation": generation[:80],
        "social": social[:80],
        "observer": observer[:80],
        "cosmos_score": score,
        "genesis_contract": build_genesis_contract(score),
    }}


def summarize(targets: list[str]) -> dict[str, object]:
    files = []
    for target in targets:
        for source in collect_sources(target):
            files.append(inspect_file(source))
    score = round(
        sum(float(item.get("cosmos_score", 0.0)) for item in files) / len(files),
        3,
    ) if files else 0.0
    return {{
        "status": "ok" if files else "no_source_files",
        "target": TARGET,
        "files": files,
        "summary": {{
            "files": len(files),
            "state": sum(len(item.get("state", [])) for item in files),
            "generation": sum(len(item.get("generation", [])) for item in files),
            "social": sum(len(item.get("social", [])) for item in files),
            "observer": sum(len(item.get("observer", [])) for item in files),
            "average_cosmos_score": score,
        }},
    }}


def main() -> None:
    targets = [arg for arg in sys.argv[1:] if arg]
    print(json.dumps(summarize(targets), ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
'''


def build_cosmos_report(target: str, scan_evidence: str) -> str:
    """Build deterministic world-engine audit output."""
    script = build_cosmos_inventory_script(target)
    return (
        "## Cosmos 确定性创世引擎审计\n"
        "- 执行锚点: 状态维度/生成能力/社会模拟/观测响应 inventory + genesis contract。\n"
        "- 审计目标: 判断系统是否能从静态程序演进为可观测、可生成、可涌现的微型世界。\n\n"
        f"## 静态创世扫描\n{scan_evidence}\n\n"
        "## Cosmos Inventory Script\n"
        "```python\n"
        f"{script}"
        "```\n\n"
        "## 执行方式\n"
        "- 保存脚本后运行：`python cosmos_inventory.py <source_file_or_directory>`。\n"
        "- 输出 `state`、`generation`、`social`、`observer` 和 `genesis_contract`。\n"
        "- 脚本只读源码，不启动仿真、不执行目标代码。\n\n"
        "## Genesis Contract\n"
        "- 世界必须声明状态维度 schema，而不是把状态散落在过程代码里。\n"
        "- 生成能力必须由 seed 驱动，保证可复现、可回放、可裁剪。\n"
        "- 智能体必须有 memory、goal、observe、decide 的最小闭环。\n"
        "- 观测者必须通过事件/视点/LOD 触发现实坍缩，不能全量预生成。\n"
        "- 每个世界 tick 必须绑定算力预算和失败降级策略。\n\n"
        "## 改造计划\n"
        "1. 把 `state` 命中点整理为统一 WorldState schema。\n"
        "2. 为 `generation` 补 seed、版本号和 deterministic replay。\n"
        "3. 为 `social` 补 Agent profile、memory store、decision loop。\n"
        "4. 为 `observer` 补事件驱动、LOD 分块和按需生成缓存。\n"
    )
