"""Deterministic fusion-boundary audit helpers."""

from __future__ import annotations


def build_fusion_inventory_script(target: str) -> str:
    """Build a dependency-free deterministic/probabilistic boundary scanner."""
    return f'''\
"""Fusion boundary inventory script generated by analysis_fusion."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

TARGET = {target!r}
SOURCE_SUFFIXES = {{".py", ".js", ".ts", ".tsx", ".jsx"}}
AI_PATTERNS = [
    (r"(?:litellm|openai|anthropic)\\.\\w+\\(", "LLM API 调用"),
    (r"(?:router|model)\\.call\\s*\\(", "模型路由调用"),
    (r"temperature\\s*=\\s*[^0]", "非零温度"),
    (r"(?:prompt|system_prompt)\\s*=", "Prompt 构造"),
    (r"\\.content\\b", "LLM 内容提取"),
]
DETERMINISTIC_PATTERNS = [
    (r"(?:Decimal|float|int)\\s*\\(", "数值转换"),
    (r"(?:hashlib|sha256|md5|checksum)", "哈希/校验"),
    (r"(?:sort|sorted|rank|compare)", "排序/比较"),
    (r"(?:assert|raise|pydantic|schema|validate)", "验证/断言"),
]
DANGER_PATTERNS = [
    (r"json\\.loads\\s*\\(\\s*(?:result|response|output|content)", "AI 输出直接 JSON 解析"),
    (r"eval\\s*\\(\\s*(?:result|response|output|content)", "AI 输出直接 eval"),
    (r"(?:cursor|execute)\\s*\\([^)]*(?:result|response|output|content)", "AI 输出进入 SQL"),
    (
        r"(?:subprocess|os\\.system)\\s*\\([^)]*(?:result|response|output|content)",
        "AI 输出进入命令",
    ),
    (r"(?:open|Path)\\s*\\([^)]*(?:result|response|output|content)", "AI 输出进入路径"),
    (r"(?:int|float|Decimal)\\s*\\(\\s*(?:result|response|output|content)", "AI 输出直接数值转换"),
]


def collect_sources(raw: str) -> list[Path]:
    path = Path(raw).expanduser().resolve()
    if not path.exists():
        return []
    if path.is_file() and path.suffix.lower() in SOURCE_SUFFIXES:
        return [path]
    if path.is_dir():
        return [
            child for child in list(path.rglob("*"))[:500]
            if child.is_file() and child.suffix.lower() in SOURCE_SUFFIXES
        ][:80]
    return []


def find_hits(source: str, patterns: list[tuple[str, str]]) -> list[dict[str, object]]:
    hits = []
    for line_no, line in enumerate(source.splitlines(), 1):
        for pattern, label in patterns:
            if re.search(pattern, line, re.IGNORECASE):
                hits.append({{"line": line_no, "label": label, "sample": line.strip()[:120]}})
    return hits


def inspect_file(path: Path) -> dict[str, object]:
    try:
        source = path.read_text(encoding="utf-8", errors="ignore")
    except OSError as exc:
        return {{"path": str(path), "found": False, "error": str(exc)}}
    ai_hits = find_hits(source, AI_PATTERNS)
    deterministic_hits = find_hits(source, DETERMINISTIC_PATTERNS)
    danger_hits = find_hits(source, DANGER_PATTERNS)
    return {{
        "path": str(path),
        "found": True,
        "ai_hits": ai_hits[:80],
        "deterministic_hits": deterministic_hits[:80],
        "danger_hits": danger_hits[:80],
        "validation_contracts": build_validation_contracts(danger_hits),
    }}


def build_validation_contracts(danger_hits: list[dict[str, object]]) -> list[dict[str, object]]:
    contracts = []
    for hit in danger_hits:
        contracts.append({{
            "line": hit["line"],
            "risk": hit["label"],
            "required_guards": [
                "类型校验",
                "格式/schema 校验",
                "范围或白名单校验",
                "失败时拒绝执行而不是自动修复",
            ],
        }})
    return contracts


def summarize(targets: list[str]) -> dict[str, object]:
    files = []
    for target in targets:
        for source in collect_sources(target):
            files.append(inspect_file(source))
    return {{
        "status": "ok" if files else "no_source_files",
        "target": TARGET,
        "files": files,
        "summary": {{
            "files": len(files),
            "ai_hits": sum(len(item.get("ai_hits", [])) for item in files),
            "deterministic_hits": sum(len(item.get("deterministic_hits", [])) for item in files),
            "danger_hits": sum(len(item.get("danger_hits", [])) for item in files),
        }},
    }}


def main() -> None:
    targets = [arg for arg in sys.argv[1:] if arg]
    print(json.dumps(summarize(targets), ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
'''


def build_fusion_report(target: str, scan_evidence: str) -> str:
    """Build deterministic fusion-boundary audit output."""
    script = build_fusion_inventory_script(target)
    return (
        "## Fusion 确定性边界审计\n"
        "- 执行锚点: 概率区/决定论区静态 inventory + 验证层契约。\n"
        "- 审计目标: AI 输出进入数值、路径、SQL、命令、JSON 等决定论边界的风险。\n\n"
        f"## 静态融合扫描\n{scan_evidence}\n\n"
        "## Fusion Inventory Script\n"
        "```python\n"
        f"{script}"
        "```\n\n"
        "## 执行方式\n"
        "- 保存脚本后运行：`python fusion_inventory.py <source_file_or_directory>`。\n"
        "- 输出 `ai_hits`、`deterministic_hits`、`danger_hits` 和验证层契约。\n"
        "- 脚本只读源码，不调用模型、不执行目标代码。\n\n"
        "## 验证层契约\n"
        "- AI 输出进入决定论代码前必须经过类型、schema、范围、白名单校验。\n"
        "- SQL/命令/路径边界必须拒绝自由文本直通，改用枚举、参数化或安全 builder。\n"
        "- 数值边界必须声明单位、范围、精度和失败行为。\n\n"
        "## 融合改造计划\n"
        "1. 先修复所有 `danger_hits`，让概率输出不能直接触发副作用。\n"
        "2. 为每个验证层补拒绝路径测试和异常输入测试。\n"
        "3. 将 inventory JSON 固化为架构边界回归样本。\n"
    )
