"""Deterministic self-evolution audit helpers."""

from __future__ import annotations


def build_genesis_inventory_script(target: str) -> str:
    """Build a dependency-free self-evolution readiness scanner."""
    return f'''\
"""Self-evolution inventory script generated by analysis_genesis."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

TARGET = {target!r}
SOURCE_SUFFIXES = {{".py", ".js", ".ts", ".tsx", ".jsx"}}
RIGIDITY_PATTERNS = [
    (r"(?:MAX_RETRIES|TIMEOUT|BUFFER_SIZE|PORT)\\s*=\\s*\\d+", "固定参数"),
    (r"if\\s+\\w+\\s*(?:==|!=)\\s*['\\\"]", "硬编码字符串分支"),
    (r"(?:api_key|secret|password|token)\\s*=\\s*['\\\"][^'\\\"]+['\\\"]", "硬编码密钥"),
    (r"FIXME|HACK|MAGIC_NUMBER|HARD_CODED", "刚性标记"),
]
EVOLUTION_PATTERNS = [
    (r"(?:importlib|__import__|import_module)\\s*\\(", "动态导入"),
    (r"(?:getattr|setattr|hasattr)\\s*\\(", "运行时属性操作"),
    (r"(?:reload|hot.?reload|watch)\\s*\\(", "热重载/监听"),
    (r"(?:plugin|extension|module).*?(?:load|register)", "插件加载"),
]
REFLECTION_PATTERNS = [
    (r"(?:inspect|ast|symtable|dis)\\.", "代码内省"),
    (r"(?:__name__|__file__|__doc__|__module__)", "自我元信息"),
    (r"(?:globals|locals|sys\\.modules)\\s*\\(", "运行时命名空间"),
]
FLEX_PATTERNS = [
    (r"(?:strategy|policy|adapter|bridge)", "可替换设计模式"),
    (r"(?:register|registry|factory)", "注册表/工厂"),
    (r"(?:ABC|Protocol|interface)", "接口抽象"),
]


def collect_sources(raw: str) -> list[Path]:
    path = Path(raw).expanduser().resolve()
    if not path.exists():
        return []
    if path.is_file() and path.suffix.lower() in SOURCE_SUFFIXES:
        return [path]
    if path.is_dir():
        return [
            child for child in list(path.rglob("*"))[:500]
            if child.is_file() and child.suffix.lower() in SOURCE_SUFFIXES
        ][:80]
    return []


def find_hits(source: str, patterns: list[tuple[str, str]]) -> list[dict[str, object]]:
    hits = []
    for line_no, line in enumerate(source.splitlines(), 1):
        for pattern, label in patterns:
            if re.search(pattern, line, re.IGNORECASE):
                hits.append({{"line": line_no, "label": label, "sample": line.strip()[:120]}})
    return hits


def inspect_file(path: Path) -> dict[str, object]:
    try:
        source = path.read_text(encoding="utf-8", errors="ignore")
    except OSError as exc:
        return {{"path": str(path), "found": False, "error": str(exc)}}
    rigidity = find_hits(source, RIGIDITY_PATTERNS)
    evolution = find_hits(source, EVOLUTION_PATTERNS)
    reflection = find_hits(source, REFLECTION_PATTERNS)
    flexibility = find_hits(source, FLEX_PATTERNS)
    return {{
        "path": str(path),
        "found": True,
        "rigidity": rigidity[:80],
        "evolution": evolution[:80],
        "reflection": reflection[:80],
        "flexibility": flexibility[:80],
        "evolution_contract": build_evolution_contract(
            rigidity, evolution, reflection, flexibility,
        ),
    }}


def build_evolution_contract(
    rigidity: list[dict[str, object]],
    evolution: list[dict[str, object]],
    reflection: list[dict[str, object]],
    flexibility: list[dict[str, object]],
) -> dict[str, object]:
    return {{
        "externalize_config_required": bool(rigidity),
        "plugin_loader_present": bool(evolution),
        "self_reflection_present": bool(reflection),
        "abstraction_present": bool(flexibility),
        "minimum_pipeline": [
            "生成候选补丁",
            "沙盒测试",
            "静态审计",
            "热加载或注册表切换",
            "失败自动回滚",
        ],
    }}


def summarize(targets: list[str]) -> dict[str, object]:
    files = []
    for target in targets:
        for source in collect_sources(target):
            files.append(inspect_file(source))
    return {{
        "status": "ok" if files else "no_source_files",
        "target": TARGET,
        "files": files,
        "summary": {{
            "files": len(files),
            "rigidity": sum(len(item.get("rigidity", [])) for item in files),
            "evolution": sum(len(item.get("evolution", [])) for item in files),
            "reflection": sum(len(item.get("reflection", [])) for item in files),
            "flexibility": sum(len(item.get("flexibility", [])) for item in files),
        }},
    }}


def main() -> None:
    targets = [arg for arg in sys.argv[1:] if arg]
    print(json.dumps(summarize(targets), ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
'''


def build_genesis_report(target: str, scan_evidence: str) -> str:
    """Build deterministic genesis self-evolution output."""
    script = build_genesis_inventory_script(target)
    return (
        "## Genesis 确定性自演化审计\n"
        "- 执行锚点: 刚性/元编程/自省/灵活性 inventory + evolution contract。\n"
        "- 审计目标: 把静态代码推向配置外化、插件注册、热加载、沙盒验证和回滚。\n\n"
        f"## 静态自演化扫描\n{scan_evidence}\n\n"
        "## Genesis Inventory Script\n"
        "```python\n"
        f"{script}"
        "```\n\n"
        "## 执行方式\n"
        "- 保存脚本后运行：`python genesis_inventory.py <source_file_or_directory>`。\n"
        "- 输出 `rigidity`、`evolution`、`reflection`、`flexibility` 和 `evolution_contract`。\n"
        "- 脚本只读源码，不执行目标代码。\n\n"
        "## Evolution Contract\n"
        "- 刚性配置必须外化为 YAML/TOML/env 或策略注册项。\n"
        "- 新能力必须先在沙盒测试，再通过注册表或插件加载，不直接覆盖稳定实现。\n"
        "- 每次热演化必须有版本记录、回滚点、静态审计和目标测试。\n\n"
        "## 实施计划\n"
        "1. 先处理 `rigidity`，降低硬编码和固定分支。\n"
        "2. 引入 registry/factory，让能力可以按名称切换。\n"
        "3. 增加 self-reflection inventory，供 Agent 自审源码结构。\n"
        "4. 建立生成补丁 -> 沙盒验证 -> 热加载 -> 回滚的演化流水线。\n"
    )
