"""Deterministic multi-agent market audit helpers."""

from __future__ import annotations


def build_macro_inventory_script(task: str) -> str:
    """Build a dependency-free market-readiness scanner."""
    return f'''\
"""Agentic market inventory script generated by analysis_macro."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

TASK = {task!r}
SOURCE_SUFFIXES = {{".py", ".js", ".ts", ".tsx", ".jsx"}}
CENTRALIZED_PATTERNS = [
    (r"(?:main|master|primary|controller|coordinator).*?(?:decide|plan|route)", "中心化决策"),
    (r"(?:router|dispatcher|scheduler)\\s*=\\s*\\w+", "单一调度器"),
    (r"(?:global|singleton)\\s+\\w+", "全局单例"),
]
DATA_MARKET_PATTERNS = [
    (r"(?:api|fetch|scrape|crawl|collect)\\s*\\(", "数据采集"),
    (r"(?:parse|extract|transform|clean)\\s*\\(", "数据处理"),
    (r"(?:cache|store|database|persist)\\s*\\(", "数据存储"),
    (r"(?:query|search|filter|aggregate)\\s*\\(", "数据查询"),
]
INCENTIVE_PATTERNS = [
    (r"(?:reward|score|rating|credit|token)\\s*[:=]", "奖励/积分"),
    (r"(?:penalty|fine|deduct|cost)\\s*[:=]", "惩罚/成本"),
    (r"(?:bid|auction|price|offer)\\s*[:=]", "竞价/定价"),
    (r"(?:budget|balance|wallet|account)\\s*[:=]", "预算/账户"),
]
COMPETITION_PATTERNS = [
    (r"(?:compete|rank|leaderboard|scoreboard)", "竞争/排名"),
    (r"(?:kill|retire|deprecate|sunset|remove)\\s*\\(", "淘汰/退出"),
    (r"(?:spawn|fork|replicate|clone)\\s*\\(", "繁殖/复制"),
    (r"(?:fitness|adapt|survive)", "适应度/生存评估"),
]


def collect_sources(raw: str) -> list[Path]:
    path = Path(raw).expanduser().resolve()
    if not path.exists():
        return []
    if path.is_file() and path.suffix.lower() in SOURCE_SUFFIXES:
        return [path]
    if path.is_dir():
        return [
            child for child in list(path.rglob("*"))[:500]
            if child.is_file() and child.suffix.lower() in SOURCE_SUFFIXES
        ][:80]
    return []


def find_hits(source: str, patterns: list[tuple[str, str]]) -> list[dict[str, object]]:
    hits = []
    for line_no, line in enumerate(source.splitlines(), 1):
        for pattern, label in patterns:
            if re.search(pattern, line, re.IGNORECASE):
                hits.append({{"line": line_no, "label": label, "sample": line.strip()[:120]}})
    return hits


def inspect_file(path: Path) -> dict[str, object]:
    try:
        source = path.read_text(encoding="utf-8", errors="ignore")
    except OSError as exc:
        return {{"path": str(path), "found": False, "error": str(exc)}}
    centralized = find_hits(source, CENTRALIZED_PATTERNS)
    data_market = find_hits(source, DATA_MARKET_PATTERNS)
    incentive = find_hits(source, INCENTIVE_PATTERNS)
    competition = find_hits(source, COMPETITION_PATTERNS)
    return {{
        "path": str(path),
        "found": True,
        "centralized": centralized[:80],
        "data_market": data_market[:80],
        "incentive": incentive[:80],
        "competition": competition[:80],
        "market_contract": build_market_contract(centralized, data_market, incentive, competition),
    }}


def build_market_contract(
    centralized: list[dict[str, object]],
    data_market: list[dict[str, object]],
    incentive: list[dict[str, object]],
    competition: list[dict[str, object]],
) -> dict[str, object]:
    return {{
        "decentralize_required": bool(centralized),
        "data_vendor_candidates": len(data_market),
        "token_economy_present": bool(incentive),
        "selection_pressure_present": bool(competition),
        "minimum_market_roles": [
            "data_vendor",
            "analyst",
            "arbitrator",
            "budget_controller",
        ],
        "minimum_controls": [
            "token_budget",
            "quality_score",
            "bankruptcy_threshold",
            "anti_monopoly_cap",
        ],
    }}


def summarize(targets: list[str]) -> dict[str, object]:
    files = []
    for target in targets:
        for source in collect_sources(target):
            files.append(inspect_file(source))
    return {{
        "status": "ok" if files else "no_source_files",
        "task": TASK,
        "files": files,
        "summary": {{
            "files": len(files),
            "centralized": sum(len(item.get("centralized", [])) for item in files),
            "data_market": sum(len(item.get("data_market", [])) for item in files),
            "incentive": sum(len(item.get("incentive", [])) for item in files),
            "competition": sum(len(item.get("competition", [])) for item in files),
        }},
    }}


def main() -> None:
    targets = [arg for arg in sys.argv[1:] if arg]
    print(json.dumps(summarize(targets), ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
'''


def build_macro_report(task: str, scan_evidence: str) -> str:
    """Build deterministic agentic market audit output."""
    script = build_macro_inventory_script(task)
    return (
        "## Macro 确定性多智能体市场审计\n"
        "- 执行锚点: 中心化/数据市场/激励/竞争 inventory + market contract。\n"
        "- 审计目标: 把单点调度拆成可交易、可评分、可淘汰的 Agent 市场。\n\n"
        f"## 静态市场化扫描\n{scan_evidence}\n\n"
        "## Market Inventory Script\n"
        "```python\n"
        f"{script}"
        "```\n\n"
        "## 执行方式\n"
        "- 保存脚本后运行：`python macro_inventory.py <source_file_or_directory>`。\n"
        "- 输出 `centralized`、`data_market`、`incentive`、`competition` 和 `market_contract`。\n"
        "- 脚本只读源码，不启动 Agent、不执行目标代码。\n\n"
        "## Market Contract\n"
        "- 每个数据商必须有价格、质量评分、可复用数据产品和退款/惩罚规则。\n"
        "- 每个分析师必须有预算、收益记录、失败成本和淘汰阈值。\n"
        "- 仲裁器必须基于真实结果或确定性验证器结算，不能由单个模型自评。\n\n"
        "## 改造计划\n"
        "1. 将 `centralized` 决策点拆成多个可竞价 Agent。\n"
        "2. 把 `data_market` 数据流封装为可定价产品。\n"
        "3. 补 token/score/budget 账本和失败惩罚。\n"
        "4. 引入排行榜、破产淘汰和成功策略复制机制。\n"
    )

