"""Deterministic LLM memory paging helpers."""

from __future__ import annotations

import re


def estimate_tokens(text: str) -> int:
    """Estimate mixed CJK/ASCII tokens without depending on a tokenizer."""
    cjk_chars = len(re.findall(r"[\u4e00-\u9fff]", text))
    ascii_chars = max(0, len(text) - cjk_chars)
    return max(1, cjk_chars // 2 + ascii_chars // 4) if text else 0


def pressure_level(tokens: int, context_window: int) -> str:
    """Map context usage to a memory pressure level."""
    if context_window <= 0:
        return "UNKNOWN"
    ratio = tokens / context_window
    if ratio >= 0.90:
        return "CRITICAL"
    if ratio >= 0.70:
        return "HIGH"
    if ratio >= 0.40:
        return "MEDIUM"
    return "LOW"


def scan_page(source_text: str) -> str:
    """Summarize context size and role distribution for paging decisions."""
    findings: list[str] = []

    total_chars = len(source_text)
    est_tokens = total_chars // 4
    findings.append(f"- 当前对话估算 Token 数: ~{est_tokens:,}")
    findings.append(f"- 对话字符数: {total_chars:,}")

    user_msgs = len(re.findall(r'"role":\s*"user"', source_text))
    assistant_msgs = len(re.findall(r'"role":\s*"assistant"', source_text))
    system_msgs = len(re.findall(r'"role":\s*"system"', source_text))
    tool_msgs = len(re.findall(r'"role":\s*"tool"', source_text))
    findings.append(
        f"- 消息分布: user={user_msgs}, assistant={assistant_msgs}, "
        f"system={system_msgs}, tool={tool_msgs}"
    )

    return "\n".join(findings)


def build_page_inventory_script(context_window: int) -> str:
    """Build a dependency-free context pressure scanner."""
    return f'''\
"""LLM memory page inventory script generated by analysis_page."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

CONTEXT_WINDOW = {context_window!r}


def read_input(args: list[str]) -> str:
    if args:
        return "\\n\\n".join(
            Path(arg).read_text(encoding="utf-8", errors="ignore")
            if Path(arg).exists()
            else arg
            for arg in args
        )
    return sys.stdin.read()


def estimate_tokens(text: str) -> int:
    cjk_chars = len(re.findall(r"[\\u4e00-\\u9fff]", text))
    ascii_chars = max(0, len(text) - cjk_chars)
    return max(1, cjk_chars // 2 + ascii_chars // 4) if text else 0


def pressure_level(tokens: int, context_window: int) -> str:
    if context_window <= 0:
        return "UNKNOWN"
    ratio = tokens / context_window
    if ratio >= 0.90:
        return "CRITICAL"
    if ratio >= 0.70:
        return "HIGH"
    if ratio >= 0.40:
        return "MEDIUM"
    return "LOW"


def role_counts(text: str) -> dict[str, int]:
    return {{
        role: len(re.findall(rf'"role"\\s*:\\s*"{{role}}"', text))
        for role in ["system", "user", "assistant", "tool"]
    }}


def summarize(text: str) -> dict[str, object]:
    tokens = estimate_tokens(text)
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    repeated = sum(1 for line in set(lines) if lines.count(line) > 1)
    ratio = tokens / CONTEXT_WINDOW if CONTEXT_WINDOW else 0.0
    return {{
        "status": "ok" if text.strip() else "empty_context",
        "context_window": CONTEXT_WINDOW,
        "chars": len(text),
        "estimated_tokens": tokens,
        "usage_ratio": round(ratio, 4),
        "pressure": pressure_level(tokens, CONTEXT_WINDOW),
        "roles": role_counts(text),
        "repeated_lines": repeated,
        "page_contract": {{
            "compact_now": ratio >= 0.70,
            "page_out_candidates": [
                "completed_subtasks",
                "raw_tool_logs",
                "superseded_exploration",
                "applied_patch_details",
            ],
            "page_in_candidates": [
                "current_objective",
                "dirty_worktree_state",
                "next_unfinished_tool",
                "latest_validation_results",
            ],
        }},
    }}


def main() -> None:
    print(json.dumps(
        summarize(read_input(sys.argv[1:])),
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
    ))


if __name__ == "__main__":
    main()
'''


def build_page_report(
    scan_evidence: str,
    context_window: int,
    session_context: str,
) -> str:
    """Build deterministic LLM paging output."""
    tokens = estimate_tokens(session_context)
    ratio = tokens / context_window if context_window > 0 else 0.0
    pressure = pressure_level(tokens, context_window)
    script = build_page_inventory_script(context_window)
    context_note = (
        "已分析传入的 session_context。"
        if session_context.strip()
        else "未传入 session_context；以下为低证据分页骨架和可运行分析脚本。"
    )
    compact_action = (
        "建议立即压缩上下文，保留目标、当前文件、验证结果和剩余任务。"
        if ratio >= 0.70
        else "当前不需要强制压缩，但应持续记录已完成任务和剩余队列。"
    )
    return (
        "## Page 确定性内存分页报告\n"
        "- 执行锚点: Token 估算/角色分布/压力等级/page_out/page_in contract。\n"
        f"- 上下文窗口: {context_window:,} tokens。\n"
        f"- 证据状态: {context_note}\n\n"
        f"## 上下文压力扫描\n{scan_evidence}\n"
        f"- 使用率估算: {ratio:.1%}\n"
        f"- 压力等级: {pressure}\n"
        f"- 调度建议: {compact_action}\n\n"
        "## Page Inventory Script\n"
        "```python\n"
        f"{script}"
        "```\n\n"
        "## 执行方式\n"
        "- 保存脚本后运行：`python page_inventory.py transcript.json` 或从 stdin 输入会话文本。\n"
        "- 输出 `estimated_tokens`、`pressure`、`roles`、`repeated_lines` 和 `page_contract`。\n\n"
        "## page_out()\n"
        "- 已完成并提交的任务细节可以压缩为 commit hash + 结果摘要。\n"
        "- 原始工具输出、重复探索和已经废弃的方案应换出。\n"
        "- 已应用 patch 的完整 diff 不必常驻，只保留文件名、目的和验证结果。\n\n"
        "## page_in()\n"
        "- 当前目标、工作树状态、剩余不可用工具、最新失败/验证输出必须常驻。\n"
        "- 下一步只换入即将处理工具的源码片段和相邻测试，不全量读仓库。\n"
    )
