"""Deterministic PID closed-loop audit helpers."""

from __future__ import annotations


def build_pid_inventory_script(target: str) -> str:
    """Build a dependency-free closed-loop readiness scanner."""
    return f'''\
"""PID closed-loop inventory script generated by analysis_pid."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

TARGET = {target!r}
SOURCE_SUFFIXES = {{".py", ".js", ".ts", ".tsx", ".jsx"}}
OPEN_LOOP_PATTERNS = [
    (r"(?:pipeline|chain|workflow)\\s*=\\s*\\[", "线性流水线"),
    (r"(?:step_1|step_2|step_3|first|second|third)\\s*[:=]", "步骤式执行"),
    (r"while\\s+True\\s*:", "无限循环"),
]
FEEDBACK_PATTERNS = [
    (r"(?:assert|verify|check|validate)\\s*\\(", "验证检查点"),
    (r"(?:status|state|progress)\\s*[=!<>]", "状态比较"),
    (r"(?:retry|fallback|recovery|rollback)\\s*\\(", "恢复机制"),
    (r"(?:log|metric|telemetry)\\s*[.(]", "指标/日志"),
]
ACCUMULATION_PATTERNS = [
    (r"total\\s*[+\\-*/]?=\\s*\\w+", "累加器"),
    (r"(?:append|extend|accumulate)\\s*\\([^)]*\\)", "数据累积"),
    (r"(?:batch|chunk|buffer)\\s*\\[", "批量缓冲"),
]
PREDICTIVE_PATTERNS = [
    (r"(?:timeout|deadline|time_limit|expiry)\\s*[=<>]", "超时/截止时间"),
    (r"(?:rate_limit|throttle|backpressure)", "速率限制/背压"),
    (r"(?:trend|slope|derivative|velocity)\\s*[=<>]", "趋势/变化率"),
]


def collect_sources(raw: str) -> list[Path]:
    path = Path(raw).expanduser().resolve()
    if not path.exists():
        return []
    if path.is_file() and path.suffix.lower() in SOURCE_SUFFIXES:
        return [path]
    if path.is_dir():
        return [
            child for child in list(path.rglob("*"))[:500]
            if child.is_file() and child.suffix.lower() in SOURCE_SUFFIXES
        ][:80]
    return []


def find_hits(source: str, patterns: list[tuple[str, str]]) -> list[dict[str, object]]:
    hits = []
    for line_no, line in enumerate(source.splitlines(), 1):
        for pattern, label in patterns:
            if re.search(pattern, line, re.IGNORECASE):
                hits.append({{"line": line_no, "label": label, "sample": line.strip()[:120]}})
    return hits


def inspect_file(path: Path) -> dict[str, object]:
    try:
        source = path.read_text(encoding="utf-8", errors="ignore")
    except OSError as exc:
        return {{"path": str(path), "found": False, "error": str(exc)}}
    open_loop = find_hits(source, OPEN_LOOP_PATTERNS)
    feedback = find_hits(source, FEEDBACK_PATTERNS)
    accumulation = find_hits(source, ACCUMULATION_PATTERNS)
    predictive = find_hits(source, PREDICTIVE_PATTERNS)
    return {{
        "path": str(path),
        "found": True,
        "open_loop": open_loop[:80],
        "feedback": feedback[:80],
        "accumulation": accumulation[:80],
        "predictive": predictive[:80],
        "pid_contract": build_pid_contract(open_loop, feedback, accumulation, predictive),
    }}


def build_pid_contract(
    open_loop: list[dict[str, object]],
    feedback: list[dict[str, object]],
    accumulation: list[dict[str, object]],
    predictive: list[dict[str, object]],
) -> dict[str, object]:
    return {{
        "p_required": len(open_loop) > 0 and len(feedback) == 0,
        "i_required": len(accumulation) > 0,
        "d_required": len(predictive) == 0,
        "minimum_gates": [
            "每个线性步骤后有状态校验",
            "累积器有上限、清零或窗口策略",
            "长循环有 timeout/deadline/backpressure",
            "失败时有 retry/fallback/rollback 或熔断",
        ],
    }}


def summarize(targets: list[str]) -> dict[str, object]:
    files = []
    for target in targets:
        for source in collect_sources(target):
            files.append(inspect_file(source))
    return {{
        "status": "ok" if files else "no_source_files",
        "target": TARGET,
        "files": files,
        "summary": {{
            "files": len(files),
            "open_loop": sum(len(item.get("open_loop", [])) for item in files),
            "feedback": sum(len(item.get("feedback", [])) for item in files),
            "accumulation": sum(len(item.get("accumulation", [])) for item in files),
            "predictive": sum(len(item.get("predictive", [])) for item in files),
        }},
    }}


def main() -> None:
    targets = [arg for arg in sys.argv[1:] if arg]
    print(json.dumps(summarize(targets), ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
'''


def build_pid_report(target: str, scan_evidence: str) -> str:
    """Build deterministic PID closed-loop audit output."""
    script = build_pid_inventory_script(target)
    return (
        "## PID 确定性闭环审计\n"
        "- 执行锚点: 开环/反馈/累积/预测 inventory + PID 改造契约。\n"
        "- 审计目标: 把线性执行改造成 P 实时校验、I 历史约束、D 趋势预防。\n\n"
        f"## 静态 PID 扫描\n{scan_evidence}\n\n"
        "## PID Inventory Script\n"
        "```python\n"
        f"{script}"
        "```\n\n"
        "## 执行方式\n"
        "- 保存脚本后运行：`python pid_inventory.py <source_file_or_directory>`。\n"
        "- 输出 `open_loop`、`feedback`、`accumulation`、`predictive` 和 `pid_contract`。\n"
        "- 脚本只读源码，不执行目标代码。\n\n"
        "## PID 改造契约\n"
        "- P: 每个步骤后必须有状态校验和偏差分支。\n"
        "- I: 累积器必须有窗口、上限、清零或历史错误权重策略。\n"
        "- D: 长循环、批处理、外部调用必须有 timeout、deadline、背压或趋势预测。\n"
        "- Actuator: 失败时必须明确继续、重试、回滚、熔断或人工接管。\n\n"
        "## 渐进式实施计划\n"
        "1. 先补 P 检查点，避免盲目串联执行。\n"
        "2. 再补 I 历史约束，避免误差和资源无限累积。\n"
        "3. 最后补 D 预测机制，提前处理超时、内存、速率和趋势风险。\n"
    )

