"""Deterministic black-box probe helpers."""

from __future__ import annotations

import re

_KNOWN_SYSTEMS = [
    (r"(?:unity|unreal|godot|cocos)", "游戏引擎"),
    (r"(?:chrome|firefox|safari|browser)", "浏览器平台"),
    (r"(?:android|ios|macos|windows|linux)", "操作系统"),
    (r"(?:openai|anthropic|google|aws|azure)", "云/API 平台"),
    (r"(?:fastapi|django|flask|express|next\.js)", "Web 框架"),
    (r"(?:postgres|mysql|redis|mongodb|sqlite)", "数据库/缓存"),
    (r"(?:grpc|protobuf|rest|graphql|websocket)", "通信协议"),
    (r"(?:pthread|epoll|libuv|boost)", "系统级库"),
]

_UNKNOWN_INDICATORS = [
    (r"(?:内部|私有|自研|闭源|proprietary|internal|private)", "私有系统"),
    (r"(?:某个|某款|某个游戏|specific game|this game)", "模糊目标引用"),
    (r"(?:没有文档|没有API|no docs|no sdk|无SDK)", "缺少文档"),
    (r"(?:逆向|反编译|reverse.?engineer|decompil)", "逆向工程"),
    (r"(?:内存地址|基址|偏移|base.?address|offset)", "内存定位风险"),
]

_PROBE_TYPES = {
    "reflection": [
        (r"(?:C#|csharp|\.NET|unity|mono)", "反射遍历对象树"),
        (r"(?:java|kotlin|android)", "Java 反射"),
        (r"(?:python|inspect|dir\(\)|模块|module)", "Python inspect 模块"),
    ],
    "memory": [
        (r"(?:内存|memory|address|地址|指针|pointer|offset|偏移)", "只生成人工内存验证清单"),
        (r"(?:cheat.?engine|cheat.?table|trainer)", "只生成 CE 表人工核验清单"),
        (r"(?:hook|detour|inject|注入)", "只生成 Hook 风险核验清单"),
    ],
    "network": [
        (r"(?:抓包|抓取|packet|wireshark|fiddler)", "网络抓包监听"),
        (r"(?:API|接口|endpoint|REST|websocket|grpc|http)", "API 探测"),
        (r"(?:protobuf|grpc|thrift)", "协议逆向"),
    ],
    "file": [
        (r"(?:配置|config|ini|yaml|json|xml)", "配置文件扫描"),
        (r"(?:存档|save|archive|pak|asset)", "资源文件解析"),
        (r"(?:log|日志|debug|trace)", "日志分析"),
    ],
}


def scan_probe(task: str, context: str) -> str:
    """Scan the probe request and estimate hallucination risk."""
    findings: list[str] = []
    combined = (task + " " + context).lower()

    known_matches: list[str] = []
    for pattern, label in _KNOWN_SYSTEMS:
        if re.search(pattern, combined, re.IGNORECASE):
            known_matches.append(label)

    if known_matches:
        findings.append(f"- 已知系统特征: {', '.join(known_matches)}")
        findings.append("  -> 幻觉风险: 低到中（仍需用真实接口回填验证）")
    else:
        findings.append("- 已知系统特征: 未匹配")
        findings.append("  -> 幻觉风险: 中到高（AI 可能编造 API）")

    unknown_matches: list[str] = []
    for pattern, label in _UNKNOWN_INDICATORS:
        if re.search(pattern, combined, re.IGNORECASE):
            unknown_matches.append(label)

    if unknown_matches:
        findings.append(f"- 未知系统特征: {', '.join(unknown_matches)}")
        findings.append("  -> 必须先探测真实接口，禁止直接编写依赖猜测的业务代码")
    else:
        findings.append("- 未知系统特征: 未检测到")

    modes = select_probe_modes(task, context)
    findings.append("- 推荐探测方式:")
    for mode in modes:
        matched_desc = next(
            (
                desc
                for pattern, desc in _PROBE_TYPES[mode]
                if re.search(pattern, combined, re.IGNORECASE)
            ),
            _fallback_mode_description(mode),
        )
        findings.append(f"  - {mode}: {matched_desc}")

    risk = 0
    if not known_matches:
        risk += 40
    if unknown_matches:
        risk += 30
    if not context.strip():
        risk += 20
    if "memory" in modes:
        risk += 10
    level = (
        "CRITICAL" if risk > 70
        else "HIGH" if risk > 45
        else "MEDIUM" if risk > 20
        else "LOW"
    )
    findings.append(f"\n- 幻觉风险评分: {risk} ({level})")
    if risk > 40:
        findings.append("  -> 先运行只读探测脚本收集真实信息，再基于实际返回结果开发")

    return "\n".join(findings)


def select_probe_modes(task: str, context: str = "") -> list[str]:
    """Select safe probe modes from task/context."""
    combined = task + " " + context
    modes: list[str] = []
    for mode, patterns in _PROBE_TYPES.items():
        if any(re.search(pattern, combined, re.IGNORECASE) for pattern, _ in patterns):
            modes.append(mode)
    if not modes:
        modes.extend(["reflection", "file"])
    return modes


def build_probe_script(task: str, context: str = "") -> str:
    """Build a dependency-free, read-only Python probe script."""
    modes = select_probe_modes(task, context)
    return f'''\
"""Read-only reconnaissance script generated by analysis_probe."""

from __future__ import annotations

import importlib
import importlib.util
import json
import os
import re
import sys
from pathlib import Path
from urllib.parse import urlparse

TASK = {task!r}
CONTEXT = {context!r}
PROBE_MODES = {modes!r}
FILE_SUFFIXES = {{".json", ".yaml", ".yml", ".ini", ".toml", ".xml", ".log", ".txt"}}


def inspect_python_object(name: str) -> dict[str, object]:
    if not name:
        return {{"target": name, "found": False, "reason": "empty target"}}
    module_name, _, attr_path = name.partition(":")
    spec = importlib.util.find_spec(module_name)
    if spec is None:
        return {{"target": name, "module": module_name, "found": False}}
    module = importlib.import_module(module_name)
    obj = module
    missing_attr = ""
    if attr_path:
        for attr in attr_path.split("."):
            if not hasattr(obj, attr):
                missing_attr = attr
                break
            obj = getattr(obj, attr)
    public = [item for item in dir(obj) if not item.startswith("_")]
    return {{
        "target": name,
        "module": module_name,
        "found": not bool(missing_attr),
        "missing_attr": missing_attr or None,
        "origin": getattr(spec, "origin", None),
        "type": type(obj).__name__,
        "public_sample": public[:50],
    }}


def scan_readonly_files(root: str) -> list[dict[str, object]]:
    base = Path(root).expanduser().resolve()
    if not base.exists():
        return [{{"path": str(base), "found": False, "reason": "not exists"}}]
    if base.is_file():
        candidates = [base]
    elif base.is_dir():
        try:
            candidates = list(base.rglob("*"))[:500]
        except OSError as exc:
            return [{{"path": str(base), "found": False, "reason": str(exc)}}]
    else:
        return [{{"path": str(base), "found": False, "reason": "unsupported path type"}}]
    results = []
    for path in candidates:
        try:
            if path.is_file() and path.suffix.lower() in FILE_SUFFIXES:
                results.append({{"path": str(path), "size": path.stat().st_size}})
        except OSError as exc:
            results.append({{"path": str(path), "error": str(exc)}})
        if len(results) >= 80:
            break
    return results


def extract_network_hints(text: str) -> list[dict[str, object]]:
    urls = sorted(set(re.findall(r"https?://[^\\s'\\\"<>]+", text)))
    hints = []
    for url in urls[:50]:
        parsed = urlparse(url)
        hints.append({{
            "url": url,
            "scheme": parsed.scheme,
            "host": parsed.netloc,
            "path": parsed.path,
            "safe_next_step": "用浏览器开发者工具或只读代理记录请求，不主动 fuzz。",
        }})
    return hints


def memory_probe_notice() -> dict[str, object]:
    return {{
        "status": "manual_safe_tooling_required",
        "reason": "脚本不会读取进程内存、不会注入、不会扫描地址空间。",
        "safe_next_step": [
            "先确认授权边界和目标进程。",
            "只记录工具输出中的模块名、版本、符号、偏移来源。",
            "禁止把未验证 offset 当作事实。",
        ],
    }}


def summarize_target(targets: list[str]) -> dict[str, object]:
    report = {{
        "status": "ok" if targets else "awaiting_targets",
        "task": TASK,
        "context_present": bool(CONTEXT.strip()),
        "cwd": os.getcwd(),
        "python": sys.version.split()[0],
        "probe_modes": PROBE_MODES,
        "targets": targets,
        "reflection": [],
        "files": [],
        "network": [],
        "memory": None,
    }}
    combined_text = " ".join([TASK, CONTEXT, *targets])
    if "reflection" in PROBE_MODES:
        for target in targets:
            if not Path(target).exists():
                report["reflection"].append(inspect_python_object(target))
    if "file" in PROBE_MODES:
        for target in targets:
            if Path(target).exists():
                report["files"].extend(scan_readonly_files(target))
    if "network" in PROBE_MODES:
        report["network"] = extract_network_hints(combined_text)
    if "memory" in PROBE_MODES:
        report["memory"] = memory_probe_notice()
    return report


def main() -> None:
    targets = [arg for arg in sys.argv[1:] if arg]
    print(json.dumps(summarize_target(targets), ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
'''


def build_probe_report(task: str, context: str, scan_evidence: str) -> str:
    """Build the deterministic probe report shown to users."""
    script = build_probe_script(task, context)
    modes = ", ".join(select_probe_modes(task, context))
    return (
        "## Probe 确定性反幻觉协议\n"
        f"- 探测模式: {modes}\n"
        "- 安全边界: 只读、无注入、无写入、无主动 fuzz。\n\n"
        f"## 静态风险扫描\n{scan_evidence}\n\n"
        "## Read-only Probe Script\n"
        "```python\n"
        f"{script}"
        "```\n\n"
        "## 执行方式\n"
        "- 保存脚本后运行：`python probe.py <module_or_object_or_directory>`。\n"
        "- Python 对象支持 `module` 或 `module:Class.method` 形式。\n"
        "- 目录/文件只读取元数据和配置/日志文件列表，不写入、不修改、不注入。\n"
        "- memory 模式只输出人工核验清单，不扫描进程内存。\n\n"
        "## 信息回填模板\n"
        "- `probe_modes`: 本次采用的探测通道。\n"
        "- `reflection[].found`: 模块或对象是否真实存在。\n"
        "- `reflection[].public_sample`: 真实公开 API 名称样本。\n"
        "- `files[]`: 可继续分析的配置/日志/资源文件路径与大小。\n"
        "- `network[]`: 从文本中提取到的 URL/host/path；没有则保持 UNKNOWN。\n"
        "- `memory.status`: 必须人工授权验证，禁止把猜测 offset 当事实。\n\n"
        "## 基于 Probe 结果的开发计划\n"
        "1. 只使用 probe 输出中真实存在的 API、路径、协议字段。\n"
        "2. 对每个 UNKNOWN 项保留探测任务，不编造函数名、endpoint 或 offset。\n"
        "3. 为发现的接口补断言：存在性、版本、返回 schema、权限边界。\n"
        "4. 将探测输出保存为回归样本，后续实现必须能在样本上复现。\n"
    )


def _fallback_mode_description(mode: str) -> str:
    return {
        "reflection": "对象/模块反射枚举",
        "memory": "只读人工内存核验",
        "network": "网络端点证据提取",
        "file": "文件元数据扫描",
    }[mode]

