"""Deterministic self-review audit helpers."""

from __future__ import annotations

import re
from pathlib import Path


def scan_self_review(files: list[Path], source_text: str) -> str:
    """Scan NaumiAgent source text for self-review health signals."""
    findings: list[str] = []
    lines = source_text.split("\n")
    total_lines = len(lines)

    findings.append(f"- 源文件: {len(files)} 个 | 总行数: {total_lines}")

    tool_registrations = re.findall(r"register\((\w+)\)", source_text)
    findings.append(f"- 工具注册调用: {len(tool_registrations)} 处")

    bare_excepts = re.findall(r"except\s*:", source_text)
    if bare_excepts:
        findings.append(f"- 🔴 裸 except (吞掉所有异常): {len(bare_excepts)} 处")
    else:
        findings.append("- ✅ 无裸 except")

    secrets = re.findall(
        r"(?:api_key|password|secret|token)\s*=\s*[\"'][^\"']{8,}",
        source_text,
        re.IGNORECASE,
    )
    if secrets:
        findings.append(f"- 🔴 疑似硬编码密钥: {len(secrets)} 处")
        for secret in secrets[:5]:
            findings.append(f"  - `{secret[:60]}`")
    else:
        findings.append("- ✅ 无硬编码密钥")

    no_return_type = re.findall(
        r"def (\w+)\([^)]*\)\s*:",
        source_text,
    )
    typed_returns = re.findall(
        r"def \w+\([^)]*\)\s*->\s+\w+",
        source_text,
    )
    untyped = len(no_return_type) - len(typed_returns)
    if untyped > 0:
        findings.append(f"- 🟡 缺少返回类型注解的函数: {untyped} 个")
    else:
        findings.append("- ✅ 所有函数都有返回类型注解")

    global_mutable = re.findall(
        r"^(\w+)\s*=\s*\{[^}]*\}|\[\]",
        source_text,
        re.MULTILINE,
    )
    if global_mutable:
        findings.append(f"- 🟡 模块级可变状态: {len(global_mutable)} 处")

    try_blocks = re.findall(r"\btry\s*:", source_text)
    if try_blocks:
        findings.append(f"- try/except 块: {len(try_blocks)} 个")

    async_defs = re.findall(r"\basync def ", source_text)
    sync_defs = re.findall(r"\bdef ", source_text)
    async_ratio = len(async_defs) / max(len(sync_defs), 1)
    findings.append(
        f"- async/sync 函数比: {len(async_defs)}/{len(sync_defs)}"
        f" ({async_ratio:.0%} async)",
    )

    test_mentions = re.findall(r"test_\w+", source_text)
    findings.append(f"- 代码中测试函数引用: {len(test_mentions)} 处")

    log_calls = re.findall(r"logger\.\w+\(", source_text)
    print_calls = re.findall(r"\bprint\(", source_text)
    findings.append(f"- logger 调用: {len(log_calls)} | print 调用: {len(print_calls)}")

    todos = re.findall(r"#\s*(?:TODO|FIXME|HACK|XXX)\b", source_text, re.IGNORECASE)
    if todos:
        findings.append(f"- 🟡 TODO/FIXME/HACK 标记: {len(todos)} 处")

    return "\n".join(findings)


def find_agent_source_dir() -> str:
    """Locate the installed or workspace NaumiAgent source directory."""
    this_file = Path(__file__).resolve()
    pkg_dir = this_file.parents[1]
    if (pkg_dir / "__init__.py").exists() and pkg_dir.name == "naumi_agent":
        return str(pkg_dir)

    import naumi_agent

    return str(Path(naumi_agent.__file__).resolve().parent)


def build_self_review_inventory_script(target: str) -> str:
    """Build a dependency-free source self-review scanner."""
    return f'''\
"""Self-review inventory script generated by analysis_self_review."""

from __future__ import annotations

import ast
import json
import re
import sys
from pathlib import Path

TARGET = {target!r}
SOURCE_SUFFIXES = {{".py"}}
SECRET_RE = re.compile(
    r"(?:api_key|password|secret|token)\\s*=\\s*[\\\"'][^\\\"']{{8,}}",
    re.IGNORECASE,
)


def collect_sources(raw: str) -> list[Path]:
    path = Path(raw).expanduser().resolve()
    if not path.exists():
        return []
    if path.is_file() and path.suffix.lower() in SOURCE_SUFFIXES:
        return [path]
    if path.is_dir():
        return [
            child for child in list(path.rglob("*.py"))[:500]
            if child.is_file()
        ][:120]
    return []


def inspect_ast(source: str) -> dict[str, object]:
    try:
        tree = ast.parse(source)
    except SyntaxError as exc:
        return {{"parse_error": str(exc), "functions": 0, "classes": 0}}
    functions = [
        node for node in ast.walk(tree)
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
    ]
    classes = [node for node in ast.walk(tree) if isinstance(node, ast.ClassDef)]
    tool_classes = [
        node.name for node in classes
        if any(getattr(base, "id", "") == "Tool" for base in node.bases)
    ]
    untyped_returns = [
        node.name for node in functions
        if node.returns is None and not node.name.startswith("_")
    ]
    long_functions = []
    for node in functions:
        end = getattr(node, "end_lineno", node.lineno)
        if end - node.lineno + 1 > 60:
            long_functions.append({{
                "name": node.name,
                "line": node.lineno,
                "lines": end - node.lineno + 1,
            }})
    return {{
        "functions": len(functions),
        "classes": len(classes),
        "tool_classes": tool_classes,
        "untyped_public_returns": untyped_returns[:80],
        "long_functions": long_functions[:80],
    }}


def inspect_file(path: Path) -> dict[str, object]:
    try:
        source = path.read_text(encoding="utf-8", errors="ignore")
    except OSError as exc:
        return {{"path": str(path), "found": False, "error": str(exc)}}
    return {{
        "path": str(path),
        "found": True,
        "lines": source.count("\\n") + 1 if source else 0,
        "bare_except": len(re.findall(r"except\\s*:", source)),
        "broad_except": len(re.findall(r"except\\s+Exception", source)),
        "hardcoded_secret": len(SECRET_RE.findall(source)),
        "logger_calls": len(re.findall(r"logger\\.\\w+\\(", source)),
        "print_calls": len(re.findall(r"\\bprint\\(", source)),
        "todo_markers": len(re.findall(r"#\\s*(?:TODO|FIXME|HACK|XXX)\\b", source, re.IGNORECASE)),
        "test_mentions": len(re.findall(r"test_\\w+", source)),
        "ast": inspect_ast(source),
    }}


def build_self_review_contract(summary: dict[str, object]) -> dict[str, object]:
    return {{
        "must_fix_bare_except": int(summary["bare_except"]) > 0,
        "must_review_secrets": int(summary["hardcoded_secret"]) > 0,
        "needs_type_pass": int(summary["untyped_public_returns"]) > 0,
        "needs_split_pass": int(summary["long_functions"]) > 0,
        "minimum_self_evolution_loop": [
            "scan",
            "rank_findings",
            "patch_one_issue",
            "targeted_tests",
            "self_review_again",
        ],
    }}


def summarize(targets: list[str]) -> dict[str, object]:
    files = []
    for target in targets:
        for source in collect_sources(target):
            files.append(inspect_file(source))
    summary = {{
        "files": len(files),
        "lines": sum(int(item.get("lines", 0)) for item in files),
        "bare_except": sum(int(item.get("bare_except", 0)) for item in files),
        "broad_except": sum(int(item.get("broad_except", 0)) for item in files),
        "hardcoded_secret": sum(int(item.get("hardcoded_secret", 0)) for item in files),
        "tool_classes": sum(
            len(item.get("ast", {{}}).get("tool_classes", [])) for item in files
        ),
        "untyped_public_returns": sum(
            len(item.get("ast", {{}}).get("untyped_public_returns", []))
            for item in files
        ),
        "long_functions": sum(
            len(item.get("ast", {{}}).get("long_functions", [])) for item in files
        ),
        "test_mentions": sum(int(item.get("test_mentions", 0)) for item in files),
    }}
    return {{
        "status": "ok" if files else "no_source_files",
        "target": TARGET,
        "files": files,
        "summary": summary,
        "self_review_contract": build_self_review_contract(summary),
    }}


def main() -> None:
    targets = [arg for arg in sys.argv[1:] if arg]
    print(json.dumps(summarize(targets), ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
'''


def build_self_review_report(
    target: str,
    focus: str,
    scan_evidence: str,
) -> str:
    """Build deterministic self-review output."""
    script = build_self_review_inventory_script(target)
    return (
        "## Self-Review 确定性自审查报告\n"
        "- 执行锚点: 源码定位/静态扫描/AST 指标/自进化闭环 contract。\n"
        f"- 审查重点: {focus or 'all'}。\n\n"
        f"## 静态自审扫描\n{scan_evidence}\n\n"
        "## Self-Review Inventory Script\n"
        "```python\n"
        f"{script}"
        "```\n\n"
        "## 执行方式\n"
        "- 保存脚本后运行：`python self_review_inventory.py <source_dir>`。\n"
        "- 输出 `bare_except`、`hardcoded_secret`、`tool_classes`、"
        "`untyped_public_returns`、`long_functions` 和 `self_review_contract`。\n"
        "- 脚本只读源码，只做 AST/正则扫描，不执行项目代码。\n\n"
        "## Self-Evolution Contract\n"
        "- 每轮只修一个高价值问题，修完运行 targeted tests。\n"
        "- 自审必须先给证据，再排序，再改代码，最后再次自审。\n"
        "- 裸异常、疑似密钥、超长公共函数和缺失类型注解优先进入修复队列。\n"
    )
