"""Deterministic self-review audit helpers."""

from __future__ import annotations


def build_self_review_inventory_script(target: str) -> str:
    """Build a dependency-free source self-review scanner."""
    return f'''\
"""Self-review inventory script generated by analysis_self_review."""

from __future__ import annotations

import ast
import json
import re
import sys
from pathlib import Path

TARGET = {target!r}
SOURCE_SUFFIXES = {{".py"}}
SECRET_RE = re.compile(
    r"(?:api_key|password|secret|token)\\s*=\\s*[\\\"'][^\\\"']{{8,}}",
    re.IGNORECASE,
)


def collect_sources(raw: str) -> list[Path]:
    path = Path(raw).expanduser().resolve()
    if not path.exists():
        return []
    if path.is_file() and path.suffix.lower() in SOURCE_SUFFIXES:
        return [path]
    if path.is_dir():
        return [
            child for child in list(path.rglob("*.py"))[:500]
            if child.is_file()
        ][:120]
    return []


def inspect_ast(source: str) -> dict[str, object]:
    try:
        tree = ast.parse(source)
    except SyntaxError as exc:
        return {{"parse_error": str(exc), "functions": 0, "classes": 0}}
    functions = [
        node for node in ast.walk(tree)
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
    ]
    classes = [node for node in ast.walk(tree) if isinstance(node, ast.ClassDef)]
    tool_classes = [
        node.name for node in classes
        if any(getattr(base, "id", "") == "Tool" for base in node.bases)
    ]
    untyped_returns = [
        node.name for node in functions
        if node.returns is None and not node.name.startswith("_")
    ]
    long_functions = []
    for node in functions:
        end = getattr(node, "end_lineno", node.lineno)
        if end - node.lineno + 1 > 60:
            long_functions.append({{
                "name": node.name,
                "line": node.lineno,
                "lines": end - node.lineno + 1,
            }})
    return {{
        "functions": len(functions),
        "classes": len(classes),
        "tool_classes": tool_classes,
        "untyped_public_returns": untyped_returns[:80],
        "long_functions": long_functions[:80],
    }}


def inspect_file(path: Path) -> dict[str, object]:
    try:
        source = path.read_text(encoding="utf-8", errors="ignore")
    except OSError as exc:
        return {{"path": str(path), "found": False, "error": str(exc)}}
    return {{
        "path": str(path),
        "found": True,
        "lines": source.count("\\n") + 1 if source else 0,
        "bare_except": len(re.findall(r"except\\s*:", source)),
        "broad_except": len(re.findall(r"except\\s+Exception", source)),
        "hardcoded_secret": len(SECRET_RE.findall(source)),
        "logger_calls": len(re.findall(r"logger\\.\\w+\\(", source)),
        "print_calls": len(re.findall(r"\\bprint\\(", source)),
        "todo_markers": len(re.findall(r"#\\s*(?:TODO|FIXME|HACK|XXX)\\b", source, re.IGNORECASE)),
        "test_mentions": len(re.findall(r"test_\\w+", source)),
        "ast": inspect_ast(source),
    }}


def build_self_review_contract(summary: dict[str, object]) -> dict[str, object]:
    return {{
        "must_fix_bare_except": int(summary["bare_except"]) > 0,
        "must_review_secrets": int(summary["hardcoded_secret"]) > 0,
        "needs_type_pass": int(summary["untyped_public_returns"]) > 0,
        "needs_split_pass": int(summary["long_functions"]) > 0,
        "minimum_self_evolution_loop": [
            "scan",
            "rank_findings",
            "patch_one_issue",
            "targeted_tests",
            "self_review_again",
        ],
    }}


def summarize(targets: list[str]) -> dict[str, object]:
    files = []
    for target in targets:
        for source in collect_sources(target):
            files.append(inspect_file(source))
    summary = {{
        "files": len(files),
        "lines": sum(int(item.get("lines", 0)) for item in files),
        "bare_except": sum(int(item.get("bare_except", 0)) for item in files),
        "broad_except": sum(int(item.get("broad_except", 0)) for item in files),
        "hardcoded_secret": sum(int(item.get("hardcoded_secret", 0)) for item in files),
        "tool_classes": sum(
            len(item.get("ast", {{}}).get("tool_classes", [])) for item in files
        ),
        "untyped_public_returns": sum(
            len(item.get("ast", {{}}).get("untyped_public_returns", []))
            for item in files
        ),
        "long_functions": sum(
            len(item.get("ast", {{}}).get("long_functions", [])) for item in files
        ),
        "test_mentions": sum(int(item.get("test_mentions", 0)) for item in files),
    }}
    return {{
        "status": "ok" if files else "no_source_files",
        "target": TARGET,
        "files": files,
        "summary": summary,
        "self_review_contract": build_self_review_contract(summary),
    }}


def main() -> None:
    targets = [arg for arg in sys.argv[1:] if arg]
    print(json.dumps(summarize(targets), ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
'''


def build_self_review_report(
    target: str,
    focus: str,
    scan_evidence: str,
) -> str:
    """Build deterministic self-review output."""
    script = build_self_review_inventory_script(target)
    return (
        "## Self-Review 确定性自审查报告\n"
        "- 执行锚点: 源码定位/静态扫描/AST 指标/自进化闭环 contract。\n"
        f"- 审查重点: {focus or 'all'}。\n\n"
        f"## 静态自审扫描\n{scan_evidence}\n\n"
        "## Self-Review Inventory Script\n"
        "```python\n"
        f"{script}"
        "```\n\n"
        "## 执行方式\n"
        "- 保存脚本后运行：`python self_review_inventory.py <source_dir>`。\n"
        "- 输出 `bare_except`、`hardcoded_secret`、`tool_classes`、"
        "`untyped_public_returns`、`long_functions` 和 `self_review_contract`。\n"
        "- 脚本只读源码，只做 AST/正则扫描，不执行项目代码。\n\n"
        "## Self-Evolution Contract\n"
        "- 每轮只修一个高价值问题，修完运行 targeted tests。\n"
        "- 自审必须先给证据，再排序，再改代码，最后再次自审。\n"
        "- 裸异常、疑似密钥、超长公共函数和缺失类型注解优先进入修复队列。\n"
    )
