"""Deterministic circadian pruning helpers."""

from __future__ import annotations

import re


def estimate_tokens(text: str) -> int:
    """Estimate mixed CJK/ASCII tokens without depending on a tokenizer."""
    cjk_chars = len(re.findall(r"[\u4e00-\u9fff]", text))
    ascii_chars = max(0, len(text) - cjk_chars)
    return max(1, cjk_chars // 2 + ascii_chars // 4) if text else 0


def build_sleep_inventory_script() -> str:
    """Build a dependency-free session consolidation scanner."""
    return '''\
"""Sleep pruning inventory script generated by analysis_sleep."""

from __future__ import annotations

import json
import re
import sys
from collections import Counter
from pathlib import Path

TOPIC_PATTERNS = [
    (r"(?:commit|提交|version|版本|changelog)", "交付/版本"),
    (r"(?:test|pytest|ruff|verify|验证)", "测试验证"),
    (r"(?:bug|error|fix|debug|crash|修复)", "问题修复"),
    (r"(?:design|arch|refactor|模块|架构|设计|重构)", "架构设计"),
    (r"(?:tool|inventory|script|工具|脚本)", "工具落地"),
]
KEEP_PATTERNS = [
    (r"(?:objective|目标|剩余|next|下一步)", "目标与剩余任务"),
    (r"(?:failed|error|失败|报错)", "失败证据"),
    (r"(?:passed|通过|验证|ruff|pytest)", "验证结果"),
    (r"(?:commit|version|版本)", "提交与版本"),
]
PRUNE_PATTERNS = [
    (r"(?:tool output|原始输出|verbose|长日志)", "原始长日志"),
    (r"(?:已完成|completed|done)", "已完成细节"),
    (r"(?:尝试|探索|dead end|废弃)", "废弃探索"),
]


def read_input(args: list[str]) -> str:
    if args:
        return "\\n\\n".join(
            Path(arg).read_text(encoding="utf-8", errors="ignore")
            if Path(arg).exists()
            else arg
            for arg in args
        )
    return sys.stdin.read()


def estimate_tokens(text: str) -> int:
    cjk_chars = len(re.findall(r"[\\u4e00-\\u9fff]", text))
    ascii_chars = max(0, len(text) - cjk_chars)
    return max(1, cjk_chars // 2 + ascii_chars // 4) if text else 0


def hits(text: str, patterns: list[tuple[str, str]]) -> dict[str, int]:
    return {
        label: len(re.findall(pattern, text, re.IGNORECASE))
        for pattern, label in patterns
        if re.findall(pattern, text, re.IGNORECASE)
    }


def key_lines(text: str, patterns: list[tuple[str, str]], limit: int = 12) -> list[str]:
    selected = []
    for line in [item.strip() for item in text.splitlines() if item.strip()]:
        if any(re.search(pattern, line, re.IGNORECASE) for pattern, _ in patterns):
            selected.append(line[:180])
    return selected[:limit]


def summarize(text: str) -> dict[str, object]:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    repeated_lines = [
        line for line, count in Counter(lines).most_common(20)
        if count > 1
    ]
    token_count = estimate_tokens(text)
    keep = key_lines(text, KEEP_PATTERNS)
    prune = key_lines(text, PRUNE_PATTERNS)
    return {
        "status": "ok" if text.strip() else "empty_context",
        "chars": len(text),
        "estimated_tokens": token_count,
        "topics": hits(text, TOPIC_PATTERNS),
        "keep_lines": keep,
        "prune_lines": prune,
        "repeated_lines": repeated_lines[:10],
        "sleep_contract": {
            "compression_target_ratio": 0.2,
            "must_keep": [
                "active_objective",
                "current_version",
                "dirty_worktree_state",
                "latest_validation",
                "remaining_tasks",
            ],
            "safe_to_prune": [
                "raw_logs_after_summary",
                "completed_patch_details",
                "superseded_attempts",
            ],
            "evolution_patch_fields": [
                "project_conventions",
                "validated_commands",
                "known_failures",
                "next_actions",
            ],
        },
    }


def main() -> None:
    print(json.dumps(
        summarize(read_input(sys.argv[1:])),
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
    ))


if __name__ == "__main__":
    main()
'''


def build_sleep_report(
    scan_evidence: str,
    session_context: str,
    combined: str,
) -> str:
    """Build deterministic sleep pruning output."""
    session_tokens = estimate_tokens(session_context)
    combined_tokens = estimate_tokens(combined)
    script = build_sleep_inventory_script()
    evidence_note = (
        "已分析传入的 session_context 和相关源码。"
        if session_context.strip()
        else "未传入 session_context；以下基于源码或空上下文生成保守修剪方案。"
    )
    return (
        "## Sleep 确定性突触修剪报告\n"
        "- 执行锚点: replay/prune/consolidate/evolution patch contract。\n"
        f"- 证据状态: {evidence_note}\n"
        f"- 会话估算: ~{session_tokens:,} tokens；合并材料估算: ~{combined_tokens:,} tokens。\n\n"
        f"## 突触修剪扫描\n{scan_evidence}\n\n"
        "## Sleep Inventory Script\n"
        "```python\n"
        f"{script}"
        "```\n\n"
        "## 执行方式\n"
        "- 保存脚本后运行：`python sleep_inventory.py transcript.md` 或从 stdin 输入会话文本。\n"
        "- 输出 `topics`、`keep_lines`、`prune_lines`、`repeated_lines` 和 `sleep_contract`。\n\n"
        "## Replay & Summarize\n"
        "- 保留当前目标、已提交版本、验证命令、剩余任务和最新失败证据。\n"
        "- 把已完成工具压缩为：工具名、commit hash、验证结果、剩余风险。\n\n"
        "## Synaptic Pruning\n"
        "- 删除已总结的原始命令输出、重复状态更新、已废弃探索路径。\n"
        "- 对已经提交的 diff 只保留文件列表和设计意图，不保留完整 patch。\n\n"
        "## Knowledge Consolidation\n"
        "- 固化项目约定：中文用户文案、工具必须有确定性逻辑、针对性测试优先。\n"
        "- 固化工作流：一个工具一个提交，版本和 CHANGELOG 随提交推进。\n\n"
        "## Evolution Patch\n"
        "- 后续工具落地优先模式：support 模块 + 可运行 inventory 脚本。\n"
        "- 每个工具都要有无 router fallback 和对应单测。\n"
        "- 下一轮从剩余 `_router_unavailable` 或工具注册/命令链路缺口继续扫描。\n"
    )
