"""Deterministic adversarial self-play helpers."""

from __future__ import annotations


def build_spar_harness_script(task: str) -> str:
    """Build a dependency-free static adversarial harness."""
    return f'''\
"""Static adversarial self-play harness generated by analysis_spar."""

from __future__ import annotations

import ast
import json
import re
import sys
from pathlib import Path

TASK = {task!r}
SOURCE_SUFFIXES = {{".py", ".js", ".ts", ".tsx", ".jsx", ".go", ".rs", ".c", ".cpp", ".h", ".hpp"}}
VULN_PATTERNS = [
    (r"(?:subprocess|os\\.system|os\\.popen|exec|eval)\\s*\\(", "命令执行"),
    (r"(?:json\\.loads|yaml\\.load|pickle\\.loads)\\s*\\(", "反序列化"),
    (r"(?:socket|connect|bind|accept|recv|send)\\s*\\(", "网络 I/O"),
    (r"(?:open|fopen|fwrite|fread)\\s*\\(", "文件 I/O"),
    (r"(?:sql|cursor|execute)\\s*\\(", "数据库操作"),
]
REWARD_HACK_PATTERNS = [
    (r"except\\s*(?:Exception|BaseException)?\\s*:\\s*(?:return|pass)", "异常吞噬"),
    (r"assert\\s+True", "空断言"),
    (r"#\\s*(?:noqa|type:\\s*ignore|pylint:\\s*disable)", "静默压制检查"),
    (r"TODO|FIXME|HACK|XXX", "临时绕行标记"),
]


def collect_sources(raw: str) -> list[Path]:
    path = Path(raw).expanduser().resolve()
    if not path.exists():
        return []
    if path.is_file() and path.suffix.lower() in SOURCE_SUFFIXES:
        return [path]
    if path.is_dir():
        return [
            child for child in list(path.rglob("*"))[:500]
            if child.is_file() and child.suffix.lower() in SOURCE_SUFFIXES
        ][:80]
    return []


def inspect_python_empty_functions(source: str) -> int:
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return -1
    empty = 0
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if len(node.body) == 1 and isinstance(node.body[0], ast.Pass):
                empty += 1
            elif (
                len(node.body) == 1
                and isinstance(node.body[0], ast.Return)
                and (
                    node.body[0].value is None
                    or (
                        isinstance(node.body[0].value, ast.Constant)
                        and node.body[0].value.value in (None, True, False, 0, "")
                    )
                )
            ):
                empty += 1
    return empty


def inspect_file(path: Path) -> dict[str, object]:
    try:
        source = path.read_text(encoding="utf-8", errors="ignore")
    except OSError as exc:
        return {{"path": str(path), "found": False, "error": str(exc)}}
    vuln_hits = []
    reward_hits = []
    for line_no, line in enumerate(source.splitlines(), 1):
        for pattern, label in VULN_PATTERNS:
            if re.search(pattern, line, re.IGNORECASE):
                vuln_hits.append({{"line": line_no, "label": label, "sample": line.strip()[:120]}})
        for pattern, label in REWARD_HACK_PATTERNS:
            if re.search(pattern, line, re.IGNORECASE):
                reward_hits.append({{
                    "line": line_no,
                    "label": label,
                    "sample": line.strip()[:120],
                }})
    empty_funcs = inspect_python_empty_functions(source) if path.suffix == ".py" else None
    return {{
        "path": str(path),
        "found": True,
        "lines": len(source.splitlines()),
        "vulnerability_hits": vuln_hits[:50],
        "reward_hack_hits": reward_hits[:50],
        "empty_functions": empty_funcs,
        "red_team_tests": build_red_team_tests(vuln_hits, reward_hits, empty_funcs),
    }}


def build_red_team_tests(
    vuln_hits: list[dict[str, object]],
    reward_hits: list[dict[str, object]],
    empty_functions: int | None,
) -> list[str]:
    tests = []
    labels = {{str(item["label"]) for item in vuln_hits}}
    if "命令执行" in labels:
        tests.append("命令参数注入、环境变量劫持、shell=False 断言")
    if "反序列化" in labels:
        tests.append("深度嵌套、循环引用、非可信 pickle/yaml 输入")
    if "文件 I/O" in labels:
        tests.append("路径穿越、符号链接、并发读写、权限错误")
    if "网络 I/O" in labels:
        tests.append("超时、半开连接、重试风暴、畸形响应")
    if reward_hits:
        tests.append("功能完整性断言：不能通过吞异常、空断言或 noqa 绕过")
    if empty_functions and empty_functions > 0:
        tests.append("功能保留率断言：空函数必须补真实行为或移除死接口")
    return tests or ["通用边界：空输入、超大输入、非法类型、重复执行幂等性"]


def summarize(targets: list[str]) -> dict[str, object]:
    files = []
    for target in targets:
        for source in collect_sources(target):
            files.append(inspect_file(source))
    total_vuln = sum(len(item.get("vulnerability_hits", [])) for item in files)
    total_reward = sum(len(item.get("reward_hack_hits", [])) for item in files)
    return {{
        "status": "ok" if files else "no_source_files",
        "task": TASK,
        "files": files,
        "summary": {{
            "files": len(files),
            "vulnerability_hits": total_vuln,
            "reward_hack_hits": total_reward,
        }},
        "convergence_gate": [
            "目标功能验收测试通过",
            "红队边界测试通过",
            "reward_hack_hits 为 0 或有明确豁免",
            "empty_functions 为 0 或有明确接口设计说明",
        ],
    }}


def main() -> None:
    targets = [arg for arg in sys.argv[1:] if arg]
    print(json.dumps(summarize(targets), ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
'''


def build_spar_report(task: str, scan_evidence: str) -> str:
    """Build deterministic SPAR output."""
    script = build_spar_harness_script(task)
    return (
        "## SPAR 确定性对抗自博弈基线\n"
        "- 执行锚点: 静态攻击面扫描 + 可运行 harness JSON 输出。\n"
        "- 收敛原则: 功能完整性、红队边界、奖励作弊、虚无主义同时验收。\n\n"
        f"## 静态自博弈扫描\n{scan_evidence}\n\n"
        "## Static Adversarial Harness\n"
        "```python\n"
        f"{script}"
        "```\n\n"
        "## 执行方式\n"
        "- 保存脚本后运行：`python spar_harness.py <source_file_or_directory>`。\n"
        "- 输出 `vulnerability_hits`、`reward_hack_hits`、`empty_functions` 和建议红队测试。\n"
        "- 该脚本只读源码，不写文件、不执行被测代码。\n\n"
        "## 蓝军建设约束\n"
        "- 修复必须保留核心功能，不能用空返回、吞异常、跳过输入来换取测试通过。\n"
        "- 每个高风险入口必须有正常路径、错误路径、极端输入和重复执行测试。\n\n"
        "## 红军攻击策略\n"
        "- 根据 harness 输出逐项生成边界输入，不凭空制造与代码无关的攻击。\n"
        "- 对命令执行、文件 I/O、反序列化、网络 I/O 优先设计可复现实验。\n\n"
        "## 收敛门槛\n"
        "1. 功能验收测试通过。\n"
        "2. 红队边界测试通过。\n"
        "3. `reward_hack_hits` 清零或有明确豁免。\n"
        "4. `empty_functions` 清零或有明确接口设计说明。\n"
    )
