"""Deterministic supervisor-tree audit helpers."""

from __future__ import annotations


def build_supervisor_inventory_script(target: str) -> str:
    """Build a dependency-free supervisor-tree readiness scanner."""
    return f'''\
"""Supervisor tree inventory script generated by analysis_supervisor."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

TARGET = {target!r}
SOURCE_SUFFIXES = {{".py", ".js", ".ts", ".tsx", ".jsx", ".yaml", ".yml", ".toml"}}
MONOLITH_PATTERNS = [
    (r"(?:while\\s+True|for\\s+.*\\s+in\\s+range)\\s*:", "长生命周期循环"),
    (r"(?:global\\s+\\w+|singleton|shared_state)", "共享全局状态"),
    (r"(?:subprocess|threading|multiprocessing).*?(?!timeout)", "无超时并发/子进程"),
    (r"(?:except\\s+Exception\\s*:\\s*(?:pass|return))", "吞掉异常"),
]
WORKER_PATTERNS = [
    (r"(?:worker|job|task|agent|runner|daemon)", "Worker/任务节点"),
    (r"(?:model|llm|generate|infer|reason)", "模型推理节点"),
    (r"(?:fetch|crawl|scrape|download|upload)", "外部 I/O 节点"),
    (r"(?:compile|exec|eval|subprocess|shell)", "代码执行节点"),
]
SUPERVISOR_PATTERNS = [
    (r"(?:supervisor|guardian|watcher|monitor|overseer)", "守护/监督者"),
    (r"(?:restart_policy|restart_strategy|max_retries)\\s*[:=]", "重启策略"),
    (r"(?:child_spec|worker_spec|process_spec)\\s*[:=]", "子节点规格"),
    (r"(?:spawn|fork|Process|Thread)\\s*\\([^)]*target", "隔离启动"),
    (r"(?:on_failure|on_error|on_crash|error_handler)\\s*[:=]", "崩溃回调"),
]
ISOLATION_PATTERNS = [
    (r"(?:try|except|catch|finally|cleanup|teardown)", "异常隔离/清理"),
    (r"(?:circuit.?breaker|bulkhead|timeout|deadline)", "熔断/舱壁/超时"),
    (r"(?:sandbox|container|isolate|quarantine|fence)", "沙盒/隔离"),
    (r"(?:snapshot|rollback|restore|checkpoint)", "快照/回滚"),
]


def collect_sources(raw: str) -> list[Path]:
    path = Path(raw).expanduser().resolve()
    if not path.exists():
        return []
    if path.is_file() and path.suffix.lower() in SOURCE_SUFFIXES:
        return [path]
    if path.is_dir():
        return [
            child for child in list(path.rglob("*"))[:500]
            if child.is_file() and child.suffix.lower() in SOURCE_SUFFIXES
        ][:80]
    return []


def find_hits(source: str, patterns: list[tuple[str, str]]) -> list[dict[str, object]]:
    hits = []
    for line_no, line in enumerate(source.splitlines(), 1):
        for pattern, label in patterns:
            if re.search(pattern, line, re.IGNORECASE):
                hits.append({{"line": line_no, "label": label, "sample": line.strip()[:120]}})
    return hits


def build_restart_contract(
    monolith: list[dict[str, object]],
    worker: list[dict[str, object]],
    supervisor: list[dict[str, object]],
    isolation: list[dict[str, object]],
) -> dict[str, object]:
    return {{
        "supervisor_required": bool(worker or monolith),
        "monolith_risk": len(monolith),
        "worker_candidates": len(worker),
        "supervisor_present": bool(supervisor),
        "isolation_present": bool(isolation),
        "minimum_restart_chain": [
            "child_spec",
            "heartbeat",
            "timeout",
            "restart_policy",
            "max_restart_intensity",
            "escalation_to_parent",
        ],
    }}


def inspect_file(path: Path) -> dict[str, object]:
    try:
        source = path.read_text(encoding="utf-8", errors="ignore")
    except OSError as exc:
        return {{"path": str(path), "found": False, "error": str(exc)}}
    monolith = find_hits(source, MONOLITH_PATTERNS)
    worker = find_hits(source, WORKER_PATTERNS)
    supervisor = find_hits(source, SUPERVISOR_PATTERNS)
    isolation = find_hits(source, ISOLATION_PATTERNS)
    return {{
        "path": str(path),
        "found": True,
        "monolith": monolith[:80],
        "worker": worker[:80],
        "supervisor": supervisor[:80],
        "isolation": isolation[:80],
        "restart_contract": build_restart_contract(
            monolith, worker, supervisor, isolation,
        ),
    }}


def summarize(targets: list[str]) -> dict[str, object]:
    files = []
    for target in targets:
        for source in collect_sources(target):
            files.append(inspect_file(source))
    return {{
        "status": "ok" if files else "no_source_files",
        "target": TARGET,
        "files": files,
        "summary": {{
            "files": len(files),
            "monolith": sum(len(item.get("monolith", [])) for item in files),
            "worker": sum(len(item.get("worker", [])) for item in files),
            "supervisor": sum(len(item.get("supervisor", [])) for item in files),
            "isolation": sum(len(item.get("isolation", [])) for item in files),
        }},
    }}


def main() -> None:
    targets = [arg for arg in sys.argv[1:] if arg]
    print(json.dumps(summarize(targets), ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
'''


def build_supervisor_report(target: str, scan_evidence: str) -> str:
    """Build deterministic supervisor-tree audit output."""
    script = build_supervisor_inventory_script(target)
    return (
        "## Supervisor 确定性守护者树审计\n"
        "- 执行锚点: 单体风险/Worker 候选/Supervisor/隔离 inventory + restart contract。\n"
        "- 审计目标: 让高风险 Worker 可以崩溃、被发现、被重启、被升级，而不是拖垮主进程。\n\n"
        f"## 静态守护者扫描\n{scan_evidence}\n\n"
        "## Supervisor Inventory Script\n"
        "```python\n"
        f"{script}"
        "```\n\n"
        "## 执行方式\n"
        "- 保存脚本后运行：`python supervisor_inventory.py <source_file_or_directory>`。\n"
        "- 输出 `monolith`、`worker`、`supervisor`、`isolation` 和 `restart_contract`。\n"
        "- 脚本只读源码，不启动进程、不重启服务。\n\n"
        "## Restart Contract\n"
        "- 每个 Worker 必须有 child_spec、heartbeat、timeout、restart_policy。\n"
        "- Supervisor 必须限制 max restart intensity，连续失败后上报父节点。\n"
        "- Worker 使用低权限沙盒；Supervisor 持有重启、回滚和隔离权限。\n"
        "- 崩溃路径必须写入 failure log，回滚优先于在线调试。\n\n"
        "## 改造计划\n"
        "1. 将 `worker` 命中点登记为 child_spec。\n"
        "2. 给每个高风险节点补 heartbeat、timeout、max_retries。\n"
        "3. 把共享全局状态迁到可恢复 snapshot 或外部状态存储。\n"
        "4. 建立 parent supervisor 的升级链路和人工介入熔断点。\n"
    )
