"""Deterministic Vibe demo scaffold helpers."""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class VibeScaffold:
    kind: str
    run_command: str
    files: tuple[tuple[str, str], ...]


def build_vibe_scaffold(description: str, tech_stack: str = "") -> VibeScaffold:
    """Build a dependency-light runnable demo scaffold."""
    clean_description = " ".join(description.strip().split()) or "Naumi Demo"
    stack = tech_stack.lower()
    if any(token in stack for token in ("node", "express", "javascript", "js")):
        return node_vibe_scaffold(clean_description)
    if any(token in stack for token in ("html", "static", "frontend", "web")):
        return static_vibe_scaffold(clean_description)
    return python_vibe_scaffold(clean_description)


def python_vibe_scaffold(description: str) -> VibeScaffold:
    """Build a stdlib-only Python web demo."""
    app_py = f'''\
"""Minimal runnable demo generated by analysis_vibe."""

from http.server import BaseHTTPRequestHandler, HTTPServer
from html import escape

DESCRIPTION = {description!r}


class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        body = f"""<!doctype html>
<html lang="zh-CN">
<head><meta charset="utf-8"><title>Naumi Vibe Demo</title></head>
<body>
  <main>
    <h1>Naumi Vibe Demo</h1>
    <p>{{escape(DESCRIPTION)}}</p>
    <form method="post">
      <input name="message" placeholder="输入一条消息">
      <button type="submit">提交</button>
    </form>
  </main>
</body>
</html>""".encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_POST(self):
        self.do_GET()


if __name__ == "__main__":
    server = HTTPServer(("127.0.0.1", 8000), Handler)
    print("Demo running at http://127.0.0.1:8000")
    server.serve_forever()
'''
    readme = vibe_readme(description, "python app.py")
    return VibeScaffold(
        kind="python-stdlib-web",
        run_command="python app.py",
        files=(("app.py", app_py), ("README.md", readme)),
    )


def node_vibe_scaffold(description: str) -> VibeScaffold:
    """Build a Node.js stdlib-only web demo."""
    server_js = f"""\
const http = require('http');

const description = {description!r};

const server = http.createServer((req, res) => {{
  res.writeHead(200, {{ 'Content-Type': 'text/html; charset=utf-8' }});
  res.end(`<!doctype html>
<html lang="zh-CN">
<head><meta charset="utf-8"><title>Naumi Vibe Demo</title></head>
<body>
  <main>
    <h1>Naumi Vibe Demo</h1>
    <p>${{description.replace(/[&<>]/g, c => ({{'&':'&amp;','<':'&lt;','>':'&gt;'}}[c]))}}</p>
    <button onclick="alert('Demo action')">执行动作</button>
  </main>
</body>
</html>`);
}});

server.listen(3000, '127.0.0.1', () => {{
  console.log('Demo running at http://127.0.0.1:3000');
}});
"""
    package_json = """\
{"scripts":{"start":"node server.js"},"dependencies":{},"devDependencies":{}}
"""
    readme = vibe_readme(description, "npm start")
    return VibeScaffold(
        kind="node-stdlib-web",
        run_command="npm start",
        files=(
            ("server.js", server_js),
            ("package.json", package_json),
            ("README.md", readme),
        ),
    )


def static_vibe_scaffold(description: str) -> VibeScaffold:
    """Build a standalone static HTML demo."""
    html = f"""\
<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Naumi Vibe Demo</title>
  <style>
    body {{ font-family: system-ui, sans-serif; margin: 40px; }}
    main {{ max-width: 760px; }}
    button {{ padding: 8px 12px; }}
  </style>
</head>
<body>
  <main>
    <h1>Naumi Vibe Demo</h1>
    <p>{escape_html(description)}</p>
    <button id="action">执行动作</button>
    <pre id="log"></pre>
  </main>
  <script>
    document.getElementById('action').addEventListener('click', () => {{
      document.getElementById('log').textContent = 'Demo action completed';
    }});
  </script>
</body>
</html>
"""
    readme = vibe_readme(description, "python -m http.server 8000")
    return VibeScaffold(
        kind="static-html",
        run_command="python -m http.server 8000",
        files=(("index.html", html), ("README.md", readme)),
    )


def vibe_readme(description: str, run_command: str) -> str:
    """Render a minimal README for generated demos."""
    return f"""\
# Naumi Vibe Demo

需求：{description}

运行：

```bash
{run_command}
```
"""


def write_vibe_scaffold(scaffold: VibeScaffold, output_dir: str) -> list[Path]:
    """Write scaffold files under output_dir without allowing path escape."""
    target = Path(os.path.expanduser(output_dir)).resolve()
    target.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for relative_name, content in scaffold.files:
        path = (target / relative_name).resolve()
        if target not in path.parents and path != target:
            raise ValueError(f"拒绝写入 output_dir 外的路径：{relative_name}")
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


def format_vibe_scaffold(scaffold: VibeScaffold, written: list[Path]) -> str:
    """Format generated scaffold files for tool output."""
    lines = [
        "## Vibe Scaffold",
        f"- 类型：{scaffold.kind}",
        f"- 运行命令：`{scaffold.run_command}`",
        f"- 文件数：{len(scaffold.files)}",
    ]
    if written:
        lines.append("- 已写入：")
        lines.extend(f"  - {path}" for path in written)
    else:
        lines.append("- 未写入文件；如需落盘，请传入 output_dir。")
    lines.append("")
    for name, content in scaffold.files:
        lang = "python" if name.endswith(".py") else "json" if name.endswith(".json") else "html"
        if name.endswith(".md"):
            lang = "markdown"
        lines.append(f"### {name}\n```{lang}\n{content[:4000]}```")
    return "\n".join(lines)


def scan_vibe_request(
    description: str,
    tech_stack: str,
    scaffold: VibeScaffold,
) -> str:
    """Summarize the concrete scaffold produced for a vibe request."""
    return (
        f"- 需求字符数：{len(description)}\n"
        f"- 技术栈偏好：{tech_stack or '未指定'}\n"
        f"- 确定性 scaffold 类型：{scaffold.kind}\n"
        f"- 生成文件：{', '.join(name for name, _ in scaffold.files)}\n"
        f"- 运行命令：{scaffold.run_command}"
    )


def escape_html(text: str) -> str:
    """Escape text for generated static HTML."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
