"""Deterministic helpers for screen-based data extraction analysis."""

from __future__ import annotations

import re

_ANTI_SCRAPE_PATTERNS = [
    (r"(?:验证码|captcha|滑块|slider|recaptcha|hCaptcha)", "人机验证"),
    (r"(?:封.?IP|rate.?limit|429|too.?many|频率限制)", "IP/频率封锁"),
    (r"(?:Cloudflare|WAF|DDoS.?protect|Akamai)", "CDN/WAF 防护"),
    (r"(?:login|登录|cookie|session|token)", "登录墙"),
    (r"(?:动态加载|lazy.?load|无限滚动|SPA)", "动态渲染"),
    (r"(?:字体加密|CSS偏移|反爬|anti.?scrape|字体反爬)", "前端反爬"),
    (r"(?:加密|encrypt|obfusc|混淆|解密)", "数据加密"),
]

_DATA_TYPES = {
    "table": [
        (r"(?:表格|table|报表|榜单|排名|list)", "表格数据"),
        (r"(?:财报|income|balance|cashflow)", "财务报表"),
    ],
    "chart": [
        (r"(?:K线|candlestick|图表|chart|走势|趋势)", "图表/走势"),
        (r"(?:MACD|RSI|布林|均线|BOLL)", "技术指标图"),
    ],
    "text": [
        (r"(?:新闻|公告|文章|正文|text)", "文本内容"),
        (r"(?:评论|comment|review|舆情)", "评论/舆情"),
    ],
    "number": [
        (r"(?:价格|price|股价|市值|PE|EPS)", "数值型数据"),
        (r"(?:成交量|volume|换手率|涨跌幅)", "交易数值"),
    ],
}

_PIPELINE_STEPS = {
    "table": [
        "定位表格边界和列分隔线",
        "按行列切分 ROI",
        "对单元格做 OCR/数字校验",
    ],
    "chart": [
        "定位坐标轴、图例和曲线颜色",
        "读取轴刻度并建立像素到数值的映射",
        "抽样曲线点并输出带置信度的数据序列",
    ],
    "text": [
        "定位正文/评论文本块",
        "按段落裁剪 ROI",
        "OCR 后做换行、标点和语言检测校验",
    ],
    "number": [
        "定位价格/指标数字区域",
        "裁剪后做数字 OCR",
        "用范围、单位和前后帧差分校验",
    ],
}


def scan_vision(task: str) -> str:
    """Scan a vision extraction request for anti-scrape and data-shape signals."""
    findings: list[str] = []
    anti_scrape = detect_anti_scrape(task)

    if anti_scrape:
        findings.append(f"- 反爬虫/访问障碍: {len(anti_scrape)} 种")
        for item in anti_scrape:
            findings.append(f"  - {item}")
        findings.append("  -> 传统 HTTP/API 路径需要先验证，视觉路径可作为稳定回退。")
    else:
        findings.append("- 反爬虫/访问障碍: 未提及（传统 API/HTML 解析可能更经济）")

    data_types = detect_data_types(task)
    if data_types:
        findings.append("- 需要提取的数据类型:")
        for dtype, label in data_types:
            findings.append(f"  - {dtype}: {label}")
    else:
        findings.append("- 数据类型: 未明确，默认生成通用 screenshot inventory 与 ROI 模板")

    findings.append("- 推荐视觉管线:")
    for step in build_pipeline_steps([dtype for dtype, _ in data_types]):
        findings.append(f"  - {step}")

    score = len(anti_scrape) * 15 + len(data_types) * 10
    level = (
        "IDEAL" if score > 40
        else "GOOD" if score > 20
        else "VIABLE" if score > 10
        else "OVERKILL"
    )
    findings.append(f"- 视觉方案适合度: {score} ({level})")
    if level == "OVERKILL":
        findings.append("  -> 先尝试 API/HTML 结构化解析，视觉方案作为回归兜底。")
    else:
        findings.append("  -> 建议保留截图样本、ROI 定义和字段校验，避免只靠主观描述。")

    return "\n".join(findings)


def detect_anti_scrape(task: str) -> list[str]:
    """Detect access obstacles mentioned in the request."""
    task_lower = task.lower()
    return [
        label
        for pattern, label in _ANTI_SCRAPE_PATTERNS
        if re.search(pattern, task_lower, re.IGNORECASE)
    ]


def detect_data_types(task: str) -> list[tuple[str, str]]:
    """Detect expected data shapes from the request."""
    task_lower = task.lower()
    matches: list[tuple[str, str]] = []
    for dtype, patterns in _DATA_TYPES.items():
        for pattern, label in patterns:
            if re.search(pattern, task_lower, re.IGNORECASE):
                matches.append((dtype, label))
                break
    return matches


def build_pipeline_steps(data_types: list[str]) -> list[str]:
    """Build extraction pipeline steps from detected data types."""
    unique_types = list(dict.fromkeys(data_types))
    steps = [
        "采集截图并记录 URL、viewport、时间戳和登录状态来源。",
        "生成 screenshot inventory，确认图片尺寸和文件指纹。",
        "为每个目标字段定义 ROI、类型、单位、置信度阈值和校验规则。",
    ]
    if not unique_types:
        steps.append("先人工标注 1-3 个 ROI 样本，再决定 OCR/图表解析/表格切分路线。")
        return steps
    for dtype in unique_types:
        steps.extend(_PIPELINE_STEPS.get(dtype, []))
    steps.append("输出 JSON/CSV，并与上一帧或已知范围做一致性校验。")
    return steps


def build_vision_inventory_script(task: str) -> str:
    """Build a dependency-free script that inventories screenshot samples."""
    data_types = [dtype for dtype, _ in detect_data_types(task)]
    anti_scrape = detect_anti_scrape(task)
    return f'''\
"""Screenshot inventory and ROI contract script generated by analysis_vision."""

from __future__ import annotations

import hashlib
import json
import struct
import sys
from pathlib import Path

TASK = {task!r}
DATA_TYPES = {data_types!r}
ANTI_SCRAPE_HINTS = {anti_scrape!r}
IMAGE_SUFFIXES = {{".png", ".jpg", ".jpeg"}}


def png_size(data: bytes) -> tuple[int | None, int | None]:
    if len(data) >= 24 and data.startswith(b"\\x89PNG\\r\\n\\x1a\\n"):
        width, height = struct.unpack(">II", data[16:24])
        return width, height
    return None, None


def jpeg_size(data: bytes) -> tuple[int | None, int | None]:
    if not data.startswith(b"\\xff\\xd8"):
        return None, None
    index = 2
    while index + 9 < len(data):
        if data[index] != 0xFF:
            index += 1
            continue
        marker = data[index + 1]
        index += 2
        if marker in (0xD8, 0xD9):
            continue
        if index + 2 > len(data):
            break
        length = int.from_bytes(data[index:index + 2], "big")
        if length < 2 or index + length > len(data):
            break
        if marker in range(0xC0, 0xC4):
            height = int.from_bytes(data[index + 3:index + 5], "big")
            width = int.from_bytes(data[index + 5:index + 7], "big")
            return width, height
        index += length
    return None, None


def inspect_image(path: Path) -> dict[str, object]:
    try:
        data = path.read_bytes()
    except OSError as exc:
        return {{"path": str(path), "found": False, "error": str(exc)}}
    suffix = path.suffix.lower()
    if suffix == ".png":
        width, height = png_size(data[:64])
    elif suffix in (".jpg", ".jpeg"):
        width, height = jpeg_size(data[:65536])
    else:
        width, height = None, None
    return {{
        "path": str(path),
        "found": True,
        "suffix": suffix,
        "size": len(data),
        "width": width,
        "height": height,
        "sha256": hashlib.sha256(data).hexdigest(),
    }}


def collect_images(raw: str) -> list[dict[str, object]]:
    path = Path(raw).expanduser().resolve()
    if not path.exists():
        return [{{"path": str(path), "found": False, "error": "not exists"}}]
    if path.is_file():
        return [inspect_image(path)]
    if path.is_dir():
        results = []
        for child in list(path.rglob("*"))[:500]:
            if child.is_file() and child.suffix.lower() in IMAGE_SUFFIXES:
                results.append(inspect_image(child))
            if len(results) >= 80:
                break
        return results
    return [{{"path": str(path), "found": False, "error": "unsupported path type"}}]


def build_roi_contract(images: list[dict[str, object]]) -> list[dict[str, object]]:
    contracts = []
    for image in images:
        if not image.get("found"):
            continue
        contracts.append({{
            "image": image["path"],
            "fields": [
                {{
                    "name": "UNKNOWN_FIELD",
                    "data_type": DATA_TYPES[0] if DATA_TYPES else "unknown",
                    "roi": {{
                        "x": 0,
                        "y": 0,
                        "width": image.get("width"),
                        "height": image.get("height"),
                    }},
                    "extractor": "ocr_or_chart_parser_required",
                    "validation": "填写类型、单位、范围、置信度阈值；禁止直接凭截图描述编造值。",
                }}
            ],
        }})
    return contracts


def summarize(targets: list[str]) -> dict[str, object]:
    images = []
    for target in targets:
        images.extend(collect_images(target))
    return {{
        "status": "ok" if images else "awaiting_screenshot_samples",
        "task": TASK,
        "data_types": DATA_TYPES,
        "anti_scrape_hints": ANTI_SCRAPE_HINTS,
        "images": images,
        "roi_contract": build_roi_contract(images),
    }}


def main() -> None:
    targets = [arg for arg in sys.argv[1:] if arg]
    print(json.dumps(summarize(targets), ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
'''


def build_vision_report(task: str, scan_evidence: str) -> str:
    """Build deterministic vision analysis output."""
    data_types = detect_data_types(task)
    type_names = ", ".join(dtype for dtype, _ in data_types) or "unknown"
    script = build_vision_inventory_script(task)
    return (
        "## Vision 确定性视觉提取方案\n"
        f"- 数据类型: {type_names}\n"
        "- 安全边界: 不绕过登录/验证码/访问控制；只基于用户可见截图或授权页面采集。\n\n"
        f"## 静态视觉扫描\n{scan_evidence}\n\n"
        "## Screenshot Inventory Script\n"
        "```python\n"
        f"{script}"
        "```\n\n"
        "## 执行方式\n"
        "- 保存脚本后运行：`python vision_inventory.py <screenshot_or_directory>`。\n"
        "- 脚本只读取 PNG/JPEG 文件，输出尺寸、sha256 和 ROI 合约模板。\n"
        "- 如果需要浏览器截图，应在已授权会话中用 Playwright/浏览器手动保存截图后再运行脚本。\n\n"
        "## 提取契约\n"
        "- 每个字段必须有 `name`、`data_type`、`roi`、`extractor`、`validation`。\n"
        "- 数字字段必须声明单位、范围、格式和置信度阈值。\n"
        "- 图表字段必须声明坐标轴 ROI、刻度映射和颜色/线型规则。\n"
        "- 表格字段必须声明表头、行列边界和空值处理策略。\n\n"
        "## 后续实现计划\n"
        "1. 用真实截图 inventory 固定样本尺寸和 hash。\n"
        "2. 人工或半自动标注 ROI 合约，禁止直接编造屏幕数据。\n"
        "3. 根据字段类型接入 OCR、表格切分或图表解析器。\n"
        "4. 用 ROI 合约和历史样本做回归测试，确保提取结果可复现。\n"
    )
