"""Deterministic disaster-recovery audit helpers."""

from __future__ import annotations


def build_watchdog_inventory_script(target: str) -> str:
    """Build a dependency-free watchdog readiness scanner."""
    return f'''\
"""Watchdog disaster inventory script generated by analysis_watchdog."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

TARGET = {target!r}
SOURCE_SUFFIXES = {{".py", ".js", ".ts", ".tsx", ".jsx", ".sh", ".yaml", ".yml"}}
INPLACE_PATTERNS = [
    (r"(?:open|write)\\([^)]*(?:__file__|sys\\.argv\\[0\\]|self\\.__class__)", "修改自身源文件"),
    (r"(?:importlib\\.reload|reload)\\s*\\(", "运行时模块重载"),
    (r"(?:exec|eval)\\s*\\(\\s*(?:open|read)", "读取并执行动态代码"),
    (r"(?:sys\\.modules|globals)\\s*\\[", "修改全局导入/命名空间"),
]
HEALTH_PATTERNS = [
    (r"(?:heartbeat|health.?check|ping|alive)", "心跳/健康检查"),
    (r"(?:timeout|deadline|time.?limit)\\s*[:=]", "超时/截止时间"),
    (r"(?:watchdog|monitor|supervisor|guard)", "外部监控"),
    (r"(?:is_alive|is_healthy|is_ready|is_running)", "存活状态检查"),
]
ROLLBACK_PATTERNS = [
    (r"(?:backup|snapshot|checkpoint|savepoint)", "备份/快照"),
    (r"(?:rollback|restore|revert|recover)\\s*\\(", "回滚/恢复"),
    (r"(?:version|revision|commit)\\s*[:=]", "版本/修订"),
]
ISOLATION_PATTERNS = [
    (r"(?:sandbox|container|docker|vm|jail)", "沙盒/容器"),
    (r"(?:isolated|separate|staging|canary)", "隔离/灰度环境"),
    (r"(?:blue.?green|feature.?flag|toggle)", "蓝绿/特性开关"),
]


def collect_sources(raw: str) -> list[Path]:
    path = Path(raw).expanduser().resolve()
    if not path.exists():
        return []
    if path.is_file() and path.suffix.lower() in SOURCE_SUFFIXES:
        return [path]
    if path.is_dir():
        return [
            child for child in list(path.rglob("*"))[:500]
            if child.is_file() and child.suffix.lower() in SOURCE_SUFFIXES
        ][:80]
    return []


def find_hits(source: str, patterns: list[tuple[str, str]]) -> list[dict[str, object]]:
    hits = []
    for line_no, line in enumerate(source.splitlines(), 1):
        for pattern, label in patterns:
            if re.search(pattern, line, re.IGNORECASE):
                hits.append({{"line": line_no, "label": label, "sample": line.strip()[:120]}})
    return hits


def inspect_file(path: Path) -> dict[str, object]:
    try:
        source = path.read_text(encoding="utf-8", errors="ignore")
    except OSError as exc:
        return {{"path": str(path), "found": False, "error": str(exc)}}
    inplace = find_hits(source, INPLACE_PATTERNS)
    health = find_hits(source, HEALTH_PATTERNS)
    rollback = find_hits(source, ROLLBACK_PATTERNS)
    isolation = find_hits(source, ISOLATION_PATTERNS)
    return {{
        "path": str(path),
        "found": True,
        "inplace": inplace[:80],
        "health": health[:80],
        "rollback": rollback[:80],
        "isolation": isolation[:80],
        "phoenix_contract": build_phoenix_contract(inplace, health, rollback, isolation),
    }}


def build_phoenix_contract(
    inplace: list[dict[str, object]],
    health: list[dict[str, object]],
    rollback: list[dict[str, object]],
    isolation: list[dict[str, object]],
) -> dict[str, object]:
    return {{
        "sandbox_required": bool(inplace),
        "external_watchdog_present": bool(health),
        "rollback_present": bool(rollback),
        "isolation_present": bool(isolation),
        "minimum_recovery_chain": [
            "pre_change_snapshot",
            "sandbox_validation",
            "heartbeat_timeout",
            "automatic_rollback",
            "failure_attribution",
            "circuit_breaker_after_repeated_failures",
        ],
    }}


def summarize(targets: list[str]) -> dict[str, object]:
    files = []
    for target in targets:
        for source in collect_sources(target):
            files.append(inspect_file(source))
    return {{
        "status": "ok" if files else "no_source_files",
        "target": TARGET,
        "files": files,
        "summary": {{
            "files": len(files),
            "inplace": sum(len(item.get("inplace", [])) for item in files),
            "health": sum(len(item.get("health", [])) for item in files),
            "rollback": sum(len(item.get("rollback", [])) for item in files),
            "isolation": sum(len(item.get("isolation", [])) for item in files),
        }},
    }}


def main() -> None:
    targets = [arg for arg in sys.argv[1:] if arg]
    print(json.dumps(summarize(targets), ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
'''


def build_watchdog_report(target: str, scan_evidence: str) -> str:
    """Build deterministic watchdog disaster-recovery output."""
    script = build_watchdog_inventory_script(target)
    return (
        "## Watchdog 确定性灾难隔离审计\n"
        "- 执行锚点: 原地修改/健康检查/回滚/隔离 inventory + phoenix contract。\n"
        "- 审计目标: AI 自修改失败后仍能被外部看门狗发现、回滚和隔离。\n\n"
        f"## 静态看门狗扫描\n{scan_evidence}\n\n"
        "## Watchdog Inventory Script\n"
        "```python\n"
        f"{script}"
        "```\n\n"
        "## 执行方式\n"
        "- 保存脚本后运行：`python watchdog_inventory.py <source_file_or_directory>`。\n"
        "- 输出 `inplace`、`health`、`rollback`、`isolation` 和 `phoenix_contract`。\n"
        "- 脚本只读源码，不重启服务、不修改文件。\n\n"
        "## Phoenix Contract\n"
        "- 自修改必须先创建 snapshot，再进入 sandbox validation。\n"
        "- 主进程必须对外发 heartbeat，由独立 watchdog 判断 timeout。\n"
        "- 发布必须有 rollback 通道、失败归因、连续失败熔断。\n"
        "- 高风险变更必须在隔离环境或蓝绿/灰度路径中验证。\n\n"
        "## 实施计划\n"
        "1. 把 `inplace` 修改点迁到沙盒副本。\n"
        "2. 为主进程补 heartbeat 文件或本地 health endpoint。\n"
        "3. 为每次自动修改补 snapshot、restore、failure log。\n"
        "4. 引入连续失败熔断，暂停自演化并要求人工确认。\n"
    )

