"""Deterministic world-model audit helpers."""

from __future__ import annotations


def build_world_inventory_script(target: str) -> str:
    """Build a dependency-free state-transition inventory script."""
    return f'''\
"""World-model inventory script generated by analysis_world."""

from __future__ import annotations

import ast
import json
import re
import sys
from pathlib import Path

TARGET = {target!r}
SOURCE_SUFFIXES = {{".py"}}
STATE_WRITE_PATTERNS = [
    (r"self\\.\\w+\\s*=", "实例属性赋值"),
    (r"\\w+\\[(?:[^\\]]+)\\]\\s*=", "索引赋值"),
    (r"\\.(?:append|extend|insert|pop|remove|clear|update)\\s*\\(", "集合修改"),
    (r"\\.(?:save|commit|write|flush|persist)\\s*\\(", "持久化写入"),
]
CAUSE_PATTERNS = [
    (r"\\bif\\b|\\bexcept\\b|\\braise\\b", "分支/异常因果"),
    (r"\\.(?:emit|dispatch|publish|send|notify)\\s*\\(", "事件发布"),
    (r"\\.(?:handle|process|on_)\\w*\\s*\\(", "事件处理"),
]


def collect_sources(raw: str) -> list[Path]:
    path = Path(raw).expanduser().resolve()
    if not path.exists():
        return []
    if path.is_file() and path.suffix.lower() in SOURCE_SUFFIXES:
        return [path]
    if path.is_dir():
        return [
            child for child in list(path.rglob("*"))[:500]
            if child.is_file() and child.suffix.lower() in SOURCE_SUFFIXES
        ][:80]
    return []


def inspect_file(path: Path) -> dict[str, object]:
    try:
        source = path.read_text(encoding="utf-8", errors="ignore")
    except OSError as exc:
        return {{"path": str(path), "found": False, "error": str(exc)}}

    lines = source.splitlines()
    writes = []
    causes = []
    for line_no, line in enumerate(lines, 1):
        for pattern, label in STATE_WRITE_PATTERNS:
            if re.search(pattern, line):
                writes.append({{"line": line_no, "label": label, "sample": line.strip()[:120]}})
        for pattern, label in CAUSE_PATTERNS:
            if re.search(pattern, line):
                causes.append({{"line": line_no, "label": label, "sample": line.strip()[:120]}})

    transitions = []
    assigned_attrs: dict[str, int] = {{}}
    read_attrs: set[str] = set()
    syntax_error = None
    try:
        tree = ast.parse(source)
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                segment = ast.get_source_segment(source, node) or ""
                if any(re.search(pattern, segment) for pattern, _ in STATE_WRITE_PATTERNS):
                    transitions.append({{
                        "function": node.name,
                        "line": node.lineno,
                        "writes_state": True,
                    }})
            if isinstance(node, ast.Attribute) and isinstance(node.value, ast.Name):
                key = f"{{node.value.id}}.{{node.attr}}"
                if isinstance(node.ctx, ast.Store):
                    assigned_attrs[key] = getattr(node, "lineno", 0)
                elif isinstance(node.ctx, ast.Load):
                    read_attrs.add(key)
    except SyntaxError as exc:
        syntax_error = str(exc)

    lost_state = [
        {{"name": name, "line": line}}
        for name, line in assigned_attrs.items()
        if name not in read_attrs
    ]
    return {{
        "path": str(path),
        "found": True,
        "lines": len(lines),
        "state_writes": writes[:80],
        "causal_events": causes[:80],
        "transitions": transitions[:80],
        "lost_state": lost_state[:80],
        "syntax_error": syntax_error,
    }}


def summarize(targets: list[str]) -> dict[str, object]:
    files = []
    for target in targets:
        for source in collect_sources(target):
            files.append(inspect_file(source))
    total_writes = sum(len(item.get("state_writes", [])) for item in files)
    total_transitions = sum(len(item.get("transitions", [])) for item in files)
    total_lost = sum(len(item.get("lost_state", [])) for item in files)
    return {{
        "status": "ok" if files else "no_python_sources",
        "target": TARGET,
        "files": files,
        "summary": {{
            "files": len(files),
            "state_writes": total_writes,
            "transitions": total_transitions,
            "lost_state": total_lost,
        }},
        "counterfactual_gate": [
            "每个状态转移函数有失败路径",
            "每个持久化写入有回滚或幂等策略",
            "每个 lost_state 有读取方、生命周期说明或删除决策",
        ],
    }}


def main() -> None:
    targets = [arg for arg in sys.argv[1:] if arg]
    print(json.dumps(summarize(targets), ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
'''


def build_world_report(target: str, scan_evidence: str) -> str:
    """Build deterministic world-model audit output."""
    script = build_world_inventory_script(target)
    return (
        "## World 确定性世界模型审计\n"
        "- 执行锚点: AST/正则状态 inventory + 可运行 JSON 审计脚本。\n"
        "- 审计目标: 状态实体、状态转移、因果链、客体永久性、反事实缺口。\n\n"
        f"## 静态世界模型扫描\n{scan_evidence}\n\n"
        "## World Inventory Script\n"
        "```python\n"
        f"{script}"
        "```\n\n"
        "## 执行方式\n"
        "- 保存脚本后运行：`python world_inventory.py <python_file_or_directory>`。\n"
        "- 输出 `state_writes`、`transitions`、`causal_events`、`lost_state`。\n"
        "- 脚本只读 Python 源码，不执行目标代码。\n\n"
        "## 状态宇宙图谱\n"
        "- `state_writes` 是候选状态实体和变更点。\n"
        "- `transitions` 是会改变世界状态的函数，应成为回归测试入口。\n"
        "- `lost_state` 是被写入但缺少读取方的实体，需要生命周期解释。\n\n"
        "## 反事实补强计划\n"
        "1. 为每个状态转移补失败路径、幂等性和回滚检查。\n"
        "2. 为每个持久化写入补提交失败、重试、重复执行的测试。\n"
        "3. 为每个 lost_state 选择读取方、生命周期文档或删除策略。\n"
        "4. 将 inventory JSON 固化为回归样本，防止状态模型退化。\n"
    )

