"""Deterministic trace-verification helpers for ZKP analysis."""

from __future__ import annotations


def build_zkp_trace_script(target: str) -> str:
    """Build a dependency-free citation/trace verifier."""
    return f'''\
"""Citation trace verifier generated by analysis_zkp."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

TARGET = {target!r}
SOURCE_SUFFIXES = {{".py", ".md", ".txt", ".json", ".yaml", ".yml"}}
UNVERIFIED_PATTERNS = [
    (r"return\\s+(?:result|response|output|content|summary)", "直接返回 AI 输出"),
    (r"(?:result|answer|summary)\\s*=\\s*(?:await\\s+)?(?:llm|model|router)", "AI 输出赋值"),
    (r"json\\.loads\\s*\\(\\s*(?:result|response|output|content)", "AI 输出反序列化"),
]
CITATION_PATTERNS = [
    (r"(?:source|reference|citation|cite)\\s*[:=]", "来源字段"),
    (r"(?:line_no|lineno|location|offset)\\s*[:=]", "位置字段"),
    (r"(?:provenance|origin|trace)\\s*[:=]", "轨迹字段"),
    (r"(?:confidence|certainty|score)\\s*[:=]", "置信度字段"),
]
VALIDATION_PATTERNS = [
    (r"(?:verify|validate|cross.?check|corroborate)\\s*\\(", "交叉验证"),
    (r"(?:hash|checksum|digest)", "哈希校验"),
    (r"(?:ground.?truth|reference|canonical)", "真值/基准"),
]


def collect_sources(raw: str) -> list[Path]:
    path = Path(raw).expanduser().resolve()
    if not path.exists():
        return []
    if path.is_file() and path.suffix.lower() in SOURCE_SUFFIXES:
        return [path]
    if path.is_dir():
        return [
            child for child in list(path.rglob("*"))[:500]
            if child.is_file() and child.suffix.lower() in SOURCE_SUFFIXES
        ][:80]
    return []


def find_hits(source: str, patterns: list[tuple[str, str]]) -> list[dict[str, object]]:
    hits = []
    for line_no, line in enumerate(source.splitlines(), 1):
        for pattern, label in patterns:
            if re.search(pattern, line, re.IGNORECASE):
                hits.append({{"line": line_no, "label": label, "sample": line.strip()[:120]}})
    return hits


def inspect_file(path: Path) -> dict[str, object]:
    try:
        source = path.read_text(encoding="utf-8", errors="ignore")
    except OSError as exc:
        return {{"path": str(path), "found": False, "error": str(exc)}}
    unverified = find_hits(source, UNVERIFIED_PATTERNS)
    citations = find_hits(source, CITATION_PATTERNS)
    validations = find_hits(source, VALIDATION_PATTERNS)
    return {{
        "path": str(path),
        "found": True,
        "unverified_outputs": unverified[:80],
        "citations": citations[:80],
        "validations": validations[:80],
        "trace_contract": build_trace_contract(unverified, citations, validations),
    }}


def build_trace_contract(
    unverified: list[dict[str, object]],
    citations: list[dict[str, object]],
    validations: list[dict[str, object]],
) -> dict[str, object]:
    return {{
        "requires_trace_tree": bool(unverified),
        "citation_fields_present": len(citations),
        "validation_fields_present": len(validations),
        "required_fields": [
            "claim_id",
            "source_path",
            "line_start",
            "line_end",
            "quoted_evidence",
            "inference_step",
            "confidence",
            "verifier_status",
        ],
    }}


def summarize(targets: list[str]) -> dict[str, object]:
    files = []
    for target in targets:
        for source in collect_sources(target):
            files.append(inspect_file(source))
    return {{
        "status": "ok" if files else "no_source_files",
        "target": TARGET,
        "files": files,
        "summary": {{
            "files": len(files),
            "unverified_outputs": sum(len(item.get("unverified_outputs", [])) for item in files),
            "citations": sum(len(item.get("citations", [])) for item in files),
            "validations": sum(len(item.get("validations", [])) for item in files),
        }},
    }}


def main() -> None:
    targets = [arg for arg in sys.argv[1:] if arg]
    print(json.dumps(summarize(targets), ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
'''


def build_zkp_report(target: str, scan_evidence: str) -> str:
    """Build deterministic ZKP trace-verification output."""
    script = build_zkp_trace_script(target)
    return (
        "## ZKP 确定性轨迹校验方案\n"
        "- 执行锚点: 不可验证输出 inventory + 引用/验证字段检测 + trace contract。\n"
        "- 审计目标: 每个 AI 结论都能追溯到来源、位置、证据和校验状态。\n\n"
        f"## 静态可验证性扫描\n{scan_evidence}\n\n"
        "## Trace Verifier Script\n"
        "```python\n"
        f"{script}"
        "```\n\n"
        "## 执行方式\n"
        "- 保存脚本后运行：`python zkp_trace.py <source_file_or_directory>`。\n"
        "- 输出 `unverified_outputs`、`citations`、`validations` 和 `trace_contract`。\n"
        "- 脚本只读源码和文本，不调用模型、不执行目标代码。\n\n"
        "## Trace Contract\n"
        "- 每个 claim 必须包含 source_path、line_start、line_end、quoted_evidence。\n"
        "- 每个推理步骤必须有 inference_step、confidence、verifier_status。\n"
        "- 引用不存在、证据不匹配、置信度缺失时必须拒绝输出高风险结论。\n\n"
        "## 实施计划\n"
        "1. 先把 `unverified_outputs` 包装成 claim 对象。\n"
        "2. 为 claim 增加引用定位和原文片段校验。\n"
        "3. 为数值/事实类 claim 增加 deterministic verifier。\n"
        "4. 将 trace JSON 固化为可验证计算回归样本。\n"
    )

