import { test, expect } from '@playwright/test'
import { mockWorkbenchApi } from './mocks'

test('selection actions preserve drafts, do not send automatically, and dismiss with Escape', async ({ page }) => {
  await mockWorkbenchApi(page)
  await page.route('**/sessions/*/messages?*', route => route.fulfill({ json: { messages: [{ id: 'm', role: 'assistant', content: '这是需要解释的真实回答片段。', metadata: {} }], total: 1 } }))
  let sends = 0
  await page.route('**/sessions/*/messages', route => { sends++; return route.fulfill({ status: 500 }) })
  await page.goto('/web2')
  const composer = page.getByRole('textbox', { name: '消息', exact: true })
  await composer.fill('已有草稿')
  await page.locator('.w2-message.assistant .w2-prose').evaluate(node => { const range = document.createRange(); range.selectNodeContents(node); window.getSelection()?.removeAllRanges(); window.getSelection()?.addRange(range) })
  const actions = page.getByRole('toolbar', { name: '选中文字操作' })
  await actions.getByRole('button', { name: '解释', exact: true }).click()
  await expect(composer).toHaveValue('已有草稿\n\n请解释以下内容：\n\n> 这是需要解释的真实回答片段。')
  expect(sends).toBe(0)
  await page.locator('.w2-message.assistant .w2-prose').evaluate(node => { (document.activeElement as HTMLElement)?.blur(); const range = document.createRange(); range.selectNodeContents(node); window.getSelection()?.removeAllRanges(); window.getSelection()?.addRange(range) })
  await expect(actions).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(actions).toHaveCount(0)
})

test('selection toolbar expands on narrow screens and accepts a custom instruction', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await mockWorkbenchApi(page)
  await page.route('**/sessions/*/messages?*', route => route.fulfill({ json: { messages: [{ id: 'm', role: 'assistant', content: '核对依赖，再执行构建。', metadata: {} }], total: 1 } }))
  await page.goto('/web2')
  const select = async () => page.locator('.w2-message.assistant .w2-prose').evaluate(node => { const range = document.createRange(); range.selectNodeContents(node); window.getSelection()?.removeAllRanges(); window.getSelection()?.addRange(range) })
  await select()
  const actions = page.getByRole('toolbar', { name: '选中文字操作' })
  await actions.getByRole('button', { name: '展开更多操作' }).click()
  await actions.getByRole('button', { name: '语法', exact: true }).click()
  const composer = page.getByRole('textbox', { name: '消息', exact: true })
  await expect(composer).toHaveValue(/纠正语法/)
  await composer.fill('')
  await select()
  const input = actions.getByRole('textbox', { name: '告诉 Agent 如何修改…' })
  await input.fill('转换为检查清单')
  await input.press('Enter')
  await expect(composer).toHaveValue(/转换为检查清单/)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('execution trace restores real run steps and exposes output on demand', async ({ page }) => {
  await mockWorkbenchApi(page)
  await page.route('**/sessions/*/messages?*', route => route.fulfill({ json: { messages: [{ id: 'm', role: 'assistant', content: '已检查文件', metadata: {} }], total: 1 } }))
  await page.route('**/sessions/*/runs', route => route.fulfill({ json: { runs: [{ id: 'r', started_at: '2026-09-11T01:00:00Z', status: 'failed', steps: [{ sequence: 1, stage: 'tool', status: 'failed', summary: 'read missing.txt', detail: '文件不存在' }] }] } }))
  await page.goto('/web2')
  const trace = page.getByLabel('执行过程', { exact: true })
  await expect(trace.getByRole('button', { name: /用时 .*失败/ })).toBeVisible()
  await trace.getByRole('button', { name: 'read missing.txt 失败' }).click()
  await expect(trace.getByText('文件不存在', { exact: true })).toBeVisible()
  await page.reload()
  await expect(trace).toBeVisible()
  await expect(page.getByRole('navigation', { name: '主导航' }).getByText('执行过程')).toHaveCount(0)
})
