import { test, expect } from '@playwright/test'
import { mockWorkbenchApi } from './mocks'

test('pinned summary keeps todos and goals outside the right panel', async ({ page }) => {
  await mockWorkbenchApi(page)
  await page.goto('/web2')
  const navigation = page.getByRole('navigation', { name: '主导航' })
  await expect(navigation.getByRole('button')).toHaveText(['新对话＋', '工具与扩展', '定时任务', '插件'])
  await expect(page.getByRole('button', { name: '删除当前会话' })).toHaveCount(0)
  for (let index = 0; index < 4; index++) {
    const controls = page.getByRole('group', { name: '面板显示控制' }).filter({ visible: true })
    await expect(controls).toHaveCount(1)
    await expect(controls.getByRole('button').nth(0)).toHaveAttribute('aria-label', '切换右侧面板')
    await expect(controls.getByRole('button').nth(1)).toHaveAttribute('aria-label', '切换执行面板')
    await controls.getByRole('button', { name: '切换执行面板' }).click()
    await expect(page.getByLabel('终端执行记录')).toBeVisible({ visible: index % 2 === 1 })
    await controls.getByRole('button', { name: '切换右侧面板' }).click()
    await expect(page.getByLabel('工作区面板')).toBeVisible({ visible: index % 2 === 1 })
  }
  await expect(page.getByRole('region', { name: '对话摘要' })).toHaveCount(0)
  const detailNavigation = page.getByRole('navigation', { name: '会话详情导航' })
  await expect(detailNavigation.getByRole('button')).toHaveText(['上下文', '依赖', '洞察'])
  await page.getByRole('button', { name: '置顶摘要' }).click()
  const summary = page.getByRole('region', { name: '置顶摘要' })
  await expect(summary).toBeVisible()
  await expect(summary.getByRole('region', { name: '待办摘要' })).toBeVisible()
  await expect(summary.locator('hr')).toHaveCount(1)
  await expect(summary.getByRole('region', { name: '目标摘要' })).toBeVisible()
  const todoBox = await summary.getByRole('region', { name: '待办摘要' }).boundingBox()
  const goalBox = await summary.getByRole('region', { name: '目标摘要' }).boundingBox()
  expect(todoBox?.y).toBeLessThan(goalBox?.y ?? 0)
  await page.keyboard.press('Escape')
  await expect(summary).toBeHidden()
  await page.getByRole('button', { name: '置顶摘要' }).click()
  await page.locator('.w2-titlebar').click({ position: { x: 500, y: 16 } })
  await expect(summary).toBeHidden()

  await page.getByRole('button', { name: '置顶摘要' }).click()
  await summary.getByRole('button', { name: '关闭置顶摘要' }).click()
  await expect(summary).toBeHidden()
  const workspacePanel = page.getByLabel('工作区面板')
  await expect(workspacePanel.getByLabel('新增待办')).toHaveCount(0)
  await expect(workspacePanel.getByText('持久目标')).toHaveCount(0)
  await page.getByRole('button', { name: '切换右侧面板' }).filter({ visible: true }).click()
  await page.reload()
  await expect(page.getByLabel('工作区面板')).toBeHidden()
  await page.getByRole('button', { name: '切换右侧面板' }).filter({ visible: true }).click()
  await expect(page.getByLabel('工作区面板')).toBeVisible()
})

test('desktop panes resize, persist and reset without collapsing the conversation', async ({ page }) => {
  await mockWorkbenchApi(page)
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.goto('/web2')

  const sidebar = page.getByLabel('项目侧栏')
  const chat = page.getByRole('region', { name: '对话', exact: true })
  const rightPanel = page.getByLabel('工作区面板')
  const leftSeparator = page.getByRole('separator', { name: '调整左侧栏宽度' })
  const rightSeparator = page.getByRole('separator', { name: '调整右侧栏宽度' })
  const initialSidebar = await sidebar.boundingBox()
  const leftHandle = await leftSeparator.boundingBox()
  expect(initialSidebar).not.toBeNull()
  expect(leftHandle).not.toBeNull()
  await page.mouse.move(leftHandle!.x + leftHandle!.width / 2, leftHandle!.y + 120)
  await page.mouse.down()
  await page.mouse.move(leftHandle!.x + leftHandle!.width / 2 + 70, leftHandle!.y + 120)
  await page.mouse.up()
  await expect.poll(async () => (await sidebar.boundingBox())?.width).toBeGreaterThan(initialSidebar!.width + 50)

  const initialRight = await rightPanel.boundingBox()
  const rightHandle = await rightSeparator.boundingBox()
  expect(initialRight).not.toBeNull()
  expect(rightHandle).not.toBeNull()
  await page.mouse.move(rightHandle!.x + rightHandle!.width / 2, rightHandle!.y + 120)
  await page.mouse.down()
  await page.mouse.move(rightHandle!.x + rightHandle!.width / 2 - 60, rightHandle!.y + 120)
  await page.mouse.up()
  await expect.poll(async () => (await rightPanel.boundingBox())?.width).toBeGreaterThan(initialRight!.width + 45)
  expect((await chat.boundingBox())?.width).toBeGreaterThanOrEqual(419)

  const savedSidebarWidth = (await sidebar.boundingBox())!.width
  const savedRightWidth = (await rightPanel.boundingBox())!.width
  await page.reload()
  await expect.poll(async () => (await sidebar.boundingBox())?.width).toBeCloseTo(savedSidebarWidth, 0)
  await expect.poll(async () => (await rightPanel.boundingBox())?.width).toBeCloseTo(savedRightWidth, 0)

  await page.getByRole('separator', { name: '调整左侧栏宽度' }).dblclick()
  await expect.poll(async () => (await sidebar.boundingBox())?.width).toBeCloseTo(240, 0)
  await page.getByRole('separator', { name: '调整右侧栏宽度' }).focus()
  await page.keyboard.press('ArrowLeft')
  await expect(page.getByRole('separator', { name: '调整右侧栏宽度' })).toHaveAttribute('aria-valuenow', /\d+/)
})
